-- One statement, same reason as 0002/0003/0004/0006: `ALTER TABLE ADD COLUMN` has no IF NOT
-- EXISTS form, so a file that mixes it with anything else cannot be re-run after a partial
-- failure.
--
-- A plain column, not a SQL `GENERATED ALWAYS AS (lower(name))` one: the key has to match
-- `nameKey()` in identity.ts exactly — NFC-normalised, Unicode-aware lower-casing — and SQLite's
-- own `lower()` only touches ASCII, which is exactly the mismatch `listCommenterSessions` already
-- documents working around in JS. The app writes this column itself on every insert and rename
-- (see d1-store.ts); migration 0008 backfills the rows that already exist and adds the index it
-- backs.
ALTER TABLE sessions ADD COLUMN name_key TEXT;
