import type { AccessibilityProfile, Material, Student } from "./types.js"

const bool = (value: number) => value === 1
const profile = (row: Record<string, unknown>): AccessibilityProfile => ({ readingLevel: String(row.reading_level), preferredLanguage: String(row.preferred_language), simplifiedLanguage: bool(Number(row.simplified_language)), symbolSupport: bool(Number(row.symbol_support)), audioSupport: bool(Number(row.audio_support)), attentionSupport: bool(Number(row.attention_support)), notes: String(row.notes) })
export class ClassroomRepository {
  constructor(private readonly db: D1Database) {}
  async listStudents(teacherId: string): Promise<Student[]> { const rows = await this.db.prepare("SELECT s.*, p.reading_level,p.preferred_language,p.simplified_language,p.symbol_support,p.audio_support,p.attention_support,p.notes FROM students s JOIN accessibility_profiles p ON p.student_id=s.id WHERE s.teacher_id=? ORDER BY s.last_name,s.first_name").bind(teacherId).all<Record<string, unknown>>(); return rows.results.map((r) => ({ id: String(r.id), teacherId: String(r.teacher_id), firstName: String(r.first_name), lastName: String(r.last_name), profile: profile(r), createdAt: String(r.created_at), updatedAt: String(r.updated_at) })) }
  async student(id: string, teacherId: string): Promise<Student | null> { const rows = await this.db.prepare("SELECT s.*, p.reading_level,p.preferred_language,p.simplified_language,p.symbol_support,p.audio_support,p.attention_support,p.notes FROM students s JOIN accessibility_profiles p ON p.student_id=s.id WHERE s.id=? AND s.teacher_id=?").bind(id, teacherId).all<Record<string, unknown>>(); return rows.results[0] ? (await this.listStudents(teacherId)).find((s) => s.id === id) ?? null : null }
  async saveStudent(student: Student): Promise<void> { const p = student.profile; await this.db.prepare("INSERT INTO students(id,teacher_id,first_name,last_name,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,updated_at=excluded.updated_at").bind(student.id, student.teacherId, student.firstName, student.lastName, student.createdAt, student.updatedAt).run(); await this.db.prepare("INSERT INTO accessibility_profiles VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET reading_level=excluded.reading_level,preferred_language=excluded.preferred_language,simplified_language=excluded.simplified_language,symbol_support=excluded.symbol_support,audio_support=excluded.audio_support,attention_support=excluded.attention_support,notes=excluded.notes").bind(student.id,p.readingLevel,p.preferredLanguage,+p.simplifiedLanguage,+p.symbolSupport,+p.audioSupport,+p.attentionSupport,p.notes).run() }
  async deleteStudent(id: string, teacherId: string): Promise<boolean> { return (await this.db.prepare("DELETE FROM students WHERE id=? AND teacher_id=?").bind(id,teacherId).run()).meta.changes > 0 }
  async listMaterials(teacherId: string): Promise<Material[]> { const r=await this.db.prepare("SELECT * FROM materials WHERE teacher_id=? ORDER BY created_at DESC").bind(teacherId).all<Record<string,unknown>>(); return r.results.map(material) }
  async material(id: string, teacherId: string): Promise<Material|null> { const r=await this.db.prepare("SELECT * FROM materials WHERE id=? AND teacher_id=?").bind(id,teacherId).first<Record<string,unknown>>(); return r?material(r):null }
  async saveMaterial(value: Material): Promise<void> { await this.db.prepare("INSERT INTO materials VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,student_id=excluded.student_id,r2_key=excluded.r2_key,updated_at=excluded.updated_at").bind(value.id,value.teacherId,value.studentId,value.title,value.body,value.r2Key,value.createdAt,value.updatedAt).run() }
  async deleteMaterial(id:string,teacherId:string):Promise<boolean>{return (await this.db.prepare("DELETE FROM materials WHERE id=? AND teacher_id=?").bind(id,teacherId).run()).meta.changes>0}
}
const material=(r:Record<string,unknown>):Material=>({id:String(r.id),teacherId:String(r.teacher_id),studentId:r.student_id?String(r.student_id):null,title:String(r.title),body:String(r.body),r2Key:r.r2_key?String(r.r2_key):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)})
