import type { ClassroomRepository } from "./repositories.js"
import type { AccessibilityProfile, ClassroomSession, Material, Student } from "./types.js"
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString(); const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const joinCode=()=>{const bytes=new Uint8Array(6);crypto.getRandomValues(bytes);return [...bytes].map((b)=>alphabet[b%alphabet.length]).join("")};
export class ClassroomService {
  constructor(private readonly repo: ClassroomRepository, private readonly db:D1Database) {}
  async createStudent(teacherId:string,input:{firstName:string;lastName:string;profile:AccessibilityProfile}) { const time=now();const student:Student={id:id(),teacherId,firstName:input.firstName,lastName:input.lastName,profile:input.profile,createdAt:time,updatedAt:time};await this.repo.saveStudent(student);return student }
  async updateStudent(id:string,teacherId:string,input:{firstName:string;lastName:string;profile:AccessibilityProfile}) { const existing=await this.repo.student(id,teacherId);if(!existing)return null;const student={...existing,...input,updatedAt:now()};await this.repo.saveStudent(student);return student }
  async createMaterial(teacherId:string,input:Pick<Material,"title"|"body"|"studentId">){if(input.studentId&&!await this.repo.student(input.studentId,teacherId))throw new Error("Student not found");const time=now();const value:Material={id:id(),teacherId,...input,r2Key:null,createdAt:time,updatedAt:time};await this.repo.saveMaterial(value);return value}
  async updateMaterial(id:string,teacherId:string,input:Pick<Material,"title"|"body"|"studentId">){const existing=await this.repo.material(id,teacherId);if(!existing)return null;if(input.studentId&&!await this.repo.student(input.studentId,teacherId))throw new Error("Student not found");const value={...existing,...input,updatedAt:now()};await this.repo.saveMaterial(value);return value}
  async createSession(teacherId:string,materialId:string,durationMinutes:number,origin:string):Promise<ClassroomSession>{if(!await this.repo.material(materialId,teacherId))throw new Error("Material not found");const createdAt=now(),expiresAt=new Date(Date.now()+durationMinutes*60_000).toISOString(),code=joinCode(),sessionId=id();await this.db.prepare("INSERT INTO classroom_sessions VALUES(?,?,?,?,?,?)").bind(sessionId,teacherId,materialId,code,expiresAt,createdAt).run();return{id:sessionId,materialId,joinCode:code,shareUrl:`${origin}/join/${code}`,expiresAt,createdAt}}
  async join(input:{joinCode:string;displayName:string}){const row=await this.db.prepare("SELECT id,material_id,expires_at FROM classroom_sessions WHERE join_code=? AND expires_at>?").bind(input.joinCode,now()).first<{id:string;material_id:string}>();if(!row)return null;const participant={id:id(),sessionId:row.id,displayName:input.displayName,joinedAt:now()};await this.db.prepare("INSERT INTO session_participants(id,session_id,display_name,joined_at) VALUES(?,?,?,?)").bind(participant.id,participant.sessionId,participant.displayName,participant.joinedAt).run();return participant}
  async complete(participantId:string,responses:Record<string,unknown>){const completedAt=now();const result=await this.db.prepare("UPDATE session_participants SET completed_at=?,responses=? WHERE id=?").bind(completedAt,JSON.stringify(responses),participantId).run();return result.meta.changes>0}
  async createParentShare(teacherId:string,materialId:string,expiresAt:string|null,origin:string){if(!await this.repo.material(materialId,teacherId))throw new Error("Material not found");const token=id().replaceAll("-","")+id().replaceAll("-","");const bytes=new TextEncoder().encode(token);const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");await this.db.prepare("INSERT INTO parent_shares VALUES(?,?,?,?,?,?)").bind(id(),teacherId,materialId,hash,expiresAt,now()).run();return{token,url:`${origin}/parent/${token}`,expiresAt}}
}
