import type { ClassroomRepository } from "./repositories.js"
import type { AccessibilityProfile, ClassroomSession, Material, Student } from "./types.js"
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString(); const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const joinCode=()=>{const bytes=new Uint8Array(6);crypto.getRandomValues(bytes);return [...bytes].map((b)=>alphabet[b%alphabet.length]).join("")};
export class ClassroomService {
  constructor(private readonly repo: ClassroomRepository, private readonly db:D1Database, private readonly bucket:R2Bucket) {}
  private async activity(teacherId:string,type:string,entityId:string,description:string){await this.db.prepare("INSERT INTO activity_logs VALUES(?,?,?,?,?,?)").bind(id(),teacherId,type,entityId,description,now()).run()}
  async createStudent(teacherId:string,input:{firstName:string;lastName:string;profile:AccessibilityProfile}) { const time=now();const student:Student={id:id(),teacherId,firstName:input.firstName,lastName:input.lastName,profile:input.profile,createdAt:time,updatedAt:time};await this.repo.saveStudent(student);await this.activity(teacherId,"profile-created",student.id,`Profile created for ${student.firstName}.`);return student }
  async updateStudent(id:string,teacherId:string,input:{firstName:string;lastName:string;profile:AccessibilityProfile}) { const existing=await this.repo.student(id,teacherId);if(!existing)return null;const student={...existing,...input,updatedAt:now()};await this.repo.saveStudent(student);await this.activity(teacherId,"profile-updated",id,`Profile updated for ${student.firstName}.`);return student }
  async createMaterial(teacherId:string,input:Pick<Material,"title"|"body"|"studentId">){if(input.studentId&&!await this.repo.student(input.studentId,teacherId))throw new Error("Student not found");const time=now(),materialId=id();const value:Material={id:materialId,teacherId,...input,r2Key:`teachers/${teacherId}/materials/${materialId}`,syncStatus:"pending",r2UploadedAt:null,syncError:null,createdAt:time,updatedAt:time};await this.repo.saveMaterial(value);await this.activity(teacherId,"material-generated",materialId,`Material generated: ${value.title}.`);return this.syncMaterialToR2(value)}
  async updateMaterial(id:string,teacherId:string,input:Pick<Material,"title"|"body"|"studentId">){const existing=await this.repo.material(id,teacherId);if(!existing)return null;if(input.studentId&&!await this.repo.student(input.studentId,teacherId))throw new Error("Student not found");const value={...existing,...input,syncStatus:"pending" as const,updatedAt:now()};await this.repo.saveMaterial(value);return this.syncMaterialToR2(value)}
  async syncMaterialToR2(material:Material):Promise<Material>{const uploading={...material,syncStatus:"uploading" as const,syncError:null,updatedAt:now()};await this.repo.saveMaterial(uploading);try{await this.bucket.put(uploading.r2Key!,uploading.body);const synced={...uploading,syncStatus:"synced" as const,r2UploadedAt:now(),updatedAt:now()};await this.repo.saveMaterial(synced);await this.activity(synced.teacherId,"material-synced",synced.id,`Material synchronized: ${synced.title}.`);return synced}catch(error){const failed={...uploading,syncStatus:"failed" as const,syncError:error instanceof Error?error.message:"Upload failed",updatedAt:now()};await this.repo.saveMaterial(failed);return failed}}
  async retryMaterial(id:string,teacherId:string){const material=await this.repo.material(id,teacherId);return material?this.syncMaterialToR2(material):null}
  async uploadMaterialContent(id:string,teacherId:string,content:ArrayBuffer){const material=await this.repo.material(id,teacherId);if(!material) return null;const uploading={...material,syncStatus:"uploading" as const,syncError:null,updatedAt:now()};await this.repo.saveMaterial(uploading);try{await this.bucket.put(uploading.r2Key!,content);const synced={...uploading,syncStatus:"synced" as const,r2UploadedAt:now(),updatedAt:now()};await this.repo.saveMaterial(synced);await this.activity(teacherId,"material-synced",id,`Material archive synchronized: ${synced.title}.`);return synced}catch(error){const failed={...uploading,syncStatus:"failed" as const,syncError:error instanceof Error?error.message:"Upload failed",updatedAt:now()};await this.repo.saveMaterial(failed);return failed}}
  async uploadMaterialFile(id:string,teacherId:string,filePath:string,content:ArrayBuffer,contentType:string|null){const material=await this.repo.material(id,teacherId);if(!material)return null;await this.bucket.put(`${material.r2Key}/web/${filePath}`,content);return material}
  async sendMaterial(teacherId:string,materialId:string,parentEmail:string){const material=await this.repo.material(materialId,teacherId);if(!material)throw new Error("Material not found");const sentAt=now();await this.db.prepare("INSERT INTO material_deliveries VALUES(?,?,?,?,?,?,?)").bind(id(),teacherId,material.studentId,materialId,parentEmail,"sent",sentAt).run();await this.activity(teacherId,"material-sent",materialId,`Material sent to parent: ${material.title}.`);return{status:"sent",sentAt}}
  async analytics(teacherId:string){const count=async(sql:string)=>Number((await this.db.prepare(sql).bind(teacherId).first<{count:number}>())?.count??0);const activities=await this.db.prepare("SELECT type,description,created_at FROM activity_logs WHERE teacher_id=? ORDER BY created_at DESC LIMIT 10").bind(teacherId).all<{type:string;description:string;created_at:string}>();return{totalProfiles:await count("SELECT COUNT(*) count FROM students WHERE teacher_id=?"),totalMaterials:await count("SELECT COUNT(*) count FROM materials WHERE teacher_id=?"),totalMaterialsSent:await count("SELECT COUNT(*) count FROM material_deliveries WHERE teacher_id=? AND status='sent'"),totalMaterialsSynced:await count("SELECT COUNT(*) count FROM materials WHERE teacher_id=? AND sync_status='synced'"),pendingUploads:await count("SELECT COUNT(*) count FROM materials WHERE teacher_id=? AND sync_status IN ('pending','uploading','failed')"),activity:activities.results}}
  async createSession(teacherId:string,materialId:string,durationMinutes:number,origin:string):Promise<ClassroomSession>{if(!await this.repo.material(materialId,teacherId))throw new Error("Material not found");const createdAt=now(),expiresAt=new Date(Date.now()+durationMinutes*60_000).toISOString(),code=joinCode(),sessionId=id();await this.db.prepare("INSERT INTO classroom_sessions VALUES(?,?,?,?,?,?)").bind(sessionId,teacherId,materialId,code,expiresAt,createdAt).run();return{id:sessionId,materialId,joinCode:code,shareUrl:`${origin}/join/${code}`,expiresAt,createdAt}}
  async join(input:{joinCode:string;displayName:string}){const row=await this.db.prepare("SELECT id,material_id,expires_at FROM classroom_sessions WHERE join_code=? AND expires_at>?").bind(input.joinCode,now()).first<{id:string;material_id:string}>();if(!row)return null;const participant={id:id(),sessionId:row.id,displayName:input.displayName,joinedAt:now()};await this.db.prepare("INSERT INTO session_participants(id,session_id,display_name,joined_at) VALUES(?,?,?,?)").bind(participant.id,participant.sessionId,participant.displayName,participant.joinedAt).run();return participant}
  async complete(participantId:string,responses:Record<string,unknown>){const completedAt=now();const result=await this.db.prepare("UPDATE session_participants SET completed_at=?,responses=? WHERE id=?").bind(completedAt,JSON.stringify(responses),participantId).run();return result.meta.changes>0}
  async createParentShare(teacherId:string,materialId:string,expiresAt:string|null,origin:string){if(!await this.repo.material(materialId,teacherId))throw new Error("Material not found");const token=id().replaceAll("-","")+id().replaceAll("-","");const bytes=new TextEncoder().encode(token);const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");await this.db.prepare("INSERT INTO parent_shares VALUES(?,?,?,?,?,?)").bind(id(),teacherId,materialId,hash,expiresAt,now()).run();return{token,url:`${origin}/parent/${token}`,expiresAt}}
}
