import fs from "node:fs"
import path from "node:path"

import { computeSpeechCacheKey, stripEmojis } from "../speech.js"
import { REGEN_SCRIPT_SOURCE } from "./regen-source.generated.js"

/**
 * Standalone TTS regeneration assets emitted into an exported ADT bundle.
 *
 * After a book is packaged, a user can edit `content/i18n/<lang>/texts.json`
 * outside ADT Studio and re-run read-aloud with `tools/regenerate-tts.mjs`.
 * That script is dependency-free and content-addressed: it recomputes each
 * unit's cache key from the current text and only calls the TTS API for lines
 * whose text changed. To detect "changed" offline without duplicating any audio,
 * we ship `regen/manifest.json` mapping each unit's textId → its baseline cache
 * key (keyed identically to {@link computeSpeechCacheKey}). The published audio
 * already in the bundle is the source of truth for unchanged units.
 *
 * See `packages/pipeline/src/regen/regenerate-tts.mjs` for the runtime logic.
 */

/** One generatable (non-manual, non-excluded, published) spoken unit. */
export interface RegenEntry {
  textId: string
  fileName: string
  text: string
}

/** Resolved, per-language speech settings that produced the shipped audio. */
export interface RegenLanguageInput {
  lang: string
  provider: string
  model: string
  voice: string
  instructions: string
  format: string
  wordHighlighting: boolean
  geminiTemperature?: number
  geminiSeed?: number
  entries: RegenEntry[]
  /** Manually uploaded/recorded units — never regenerated by the script. */
  manualTextIds: string[]
  /** Baseline text for manual units, so the script can warn when it changed. */
  manualTexts: Record<string, string>
}

export interface EmitRegenAssetsInput {
  /** The `adt/` bundle directory (contains `content/`, `assets/`, ...). */
  adtDir: string
  languages: RegenLanguageInput[]
}

const REGEN_MANIFEST_VERSION = 1

function writeJson(filePath: string, data: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n")
}

/**
 * Write the manifest (per-unit baseline cache keys), editable config, README,
 * and the regenerator script into the bundle. Returns the number of units
 * recorded (0 if there is nothing regeneratable).
 */
export function emitRegenAssets(input: EmitRegenAssetsInput): number {
  const { adtDir, languages } = input

  const generatable = languages.filter((l) => l.entries.length > 0)
  if (generatable.length === 0) return 0

  const configLanguages: Record<string, unknown> = {}
  const manifestLanguages: Record<string, unknown> = {}
  let unitsRecorded = 0

  for (const lang of languages) {
    configLanguages[lang.lang] = {
      provider: lang.provider,
      model: lang.model,
      voice: lang.voice,
      instructions: lang.instructions,
      format: lang.format,
      wordHighlighting: lang.wordHighlighting,
    }

    // Baseline cache key per unit: identifies the text (+ voice/model/
    // instructions/provider) that produced the audio currently in the bundle.
    // The regenerator recomputes each key from the edited text and re-records
    // only the units whose key changed — no audio is duplicated.
    const entries: Record<string, string> = {}
    for (const entry of lang.entries) {
      entries[entry.textId] = computeSpeechCacheKey({
        text: stripEmojis(entry.text).trim(),
        voice: lang.voice,
        model: lang.model,
        instructions: lang.instructions,
        provider: lang.provider,
        geminiTemperature: lang.geminiTemperature,
        geminiSeed: lang.geminiSeed,
      })
      unitsRecorded++
    }

    manifestLanguages[lang.lang] = {
      entries,
      manualTextIds: lang.manualTextIds,
      manualTexts: lang.manualTexts,
      geminiTemperature: lang.geminiTemperature ?? null,
      geminiSeed: lang.geminiSeed ?? null,
    }
  }

  writeJson(path.join(adtDir, "regen", "manifest.json"), {
    version: REGEN_MANIFEST_VERSION,
    note: "Internal bookkeeping for tools/regenerate-tts.mjs — do not edit.",
    languages: manifestLanguages,
  })

  writeJson(path.join(adtDir, "tools", "tts.config.json"), {
    $comment:
      "Edit content/i18n/<lang>/texts.json then run tools/regenerate-tts.mjs to re-record only changed lines. " +
      "Change a voice/model/instructions below to re-record a whole language. Set API keys via the env vars named here.",
    languages: configLanguages,
    providers: {
      openai: { apiKeyEnv: "OPENAI_API_KEY" },
      gemini: {
        apiKeyEnv: "GEMINI_API_KEY",
        supported: false,
        note: "Gemini regeneration is not yet supported by this standalone script — regenerate Gemini languages from ADT Studio.",
      },
      azure: {
        apiKeyEnv: "AZURE_SPEECH_KEY",
        region: "",
        supported: false,
        note: "Azure regeneration is not yet supported by this standalone script — regenerate Azure languages from ADT Studio.",
      },
    },
    whisper: { apiKeyEnv: "OPENAI_API_KEY" },
  })

  const toolsDir = path.join(adtDir, "tools")
  fs.mkdirSync(toolsDir, { recursive: true })
  fs.writeFileSync(path.join(toolsDir, "regenerate-tts.mjs"), REGEN_SCRIPT_SOURCE)
  fs.writeFileSync(path.join(toolsDir, "README.md"), REGEN_README)

  return unitsRecorded
}

const REGEN_README = `# Regenerate read-aloud audio (TTS)

This ADT bundle ships a small script that regenerates its read-aloud audio after
you edit the book's text — for example when a coding agent changes a line in
\`content/i18n/<lang>/texts.json\`.

It is **dependency-free**: it only needs **Node.js 20+**. No \`npm install\`.

## How it works

Audio is content-addressed. Each spoken unit's cache key is a hash of its
*text + voice + model + instructions + provider*. This bundle records the
baseline key for every unit's current audio in \`regen/manifest.json\`. When you
run the script it recomputes each unit's key from the **current** text:

- key unchanged (you didn't touch that line) → kept as-is, **no API call**
- key changed (you edited that line) → re-synthesized via the TTS API

So editing one line costs exactly one TTS call; everything else is free. No audio
is duplicated — the audio already in \`content/i18n/<lang>/audio/\` is the source
of truth for lines you didn't change.

## Steps

1. Edit the text in \`content/i18n/<lang>/texts.json\`. The reader renders text
   from this file at runtime, so this is the source of truth for what is spoken.
2. Set your API key:

   \`\`\`sh
   export OPENAI_API_KEY=sk-...
   \`\`\`

3. Preview what would change (no API calls, no cost):

   \`\`\`sh
   node tools/regenerate-tts.mjs --dry-run
   \`\`\`

4. Regenerate:

   \`\`\`sh
   node tools/regenerate-tts.mjs
   \`\`\`

   Limit to one language with \`--lang es-uy\`.

## What it does and doesn't touch

- **Only changed lines** are re-recorded. Unchanged audio is left byte-for-byte
  identical.
- **Word highlighting**: if this book uses highlighting, the script re-runs
  alignment (OpenAI Whisper) for the lines it re-recorded and updates
  \`content/i18n/<lang>/timecode/timecode_output.json\`. This needs
  \`OPENAI_API_KEY\` too.
- **Manually recorded audio is never overwritten.** If you edited the text of a
  manually recorded line, the script warns you (the recording can't be
  auto-updated) — re-record it in ADT Studio if needed.

## Configuration

\`tools/tts.config.json\` holds the per-language voice/model/instructions this book
was built with. Change a value there to re-record a whole language in a different
voice. API keys are read from the environment variables named in that file
(never store keys in the file).

## Provider support

This script currently regenerates **OpenAI** voices. Gemini and Azure languages
are recognized but not yet regeneratable here — regenerate those from within ADT
Studio. (The bundle records which provider each language used.)

## Notes

- Regenerated files are not re-compressed the way ADT Studio compresses its
  output, so a re-recorded line may differ slightly in size/encoding from the
  originals. This does not affect playback.
`
