/* eslint-disable lingui/no-unlocalized-strings -- Internal, English-only review report for the team;
 * this data is rendered by the dev-only /redesign-review route and is never localised. */
import type { Review } from "./types"

export const CONTRAST_REVIEW: Review = {
  id: "contrast",
  label: "Dark contrast",
  title: "Dark-theme contrast review",
  lead: "WCAG ratios computed from the .dark token values, not eyeballed. Targets: 4.5:1 body, 3:1 large text / meaningful glyphs, borders and state indicators.",
  method:
    "OKLCH → Oklab → linear sRGB → relative luminance, with every /alpha composited over its real parent surface (--background 0.15, --card 0.17, --sidebar 0.13, --muted 0.23). 180 checks; 98 fall below target in dark, ~70 actionable after excluding decorative-only. Scripts left in .context/contrast.mjs + measure*.mjs.",
  findings: [
    {
      id: "d-1",
      severity: "blocker",
      category: "Brand-ramp direction",
      where: "LanguageSection.tsx:67 (+ :45)",
      problem:
        "The selected language label is 1.21:1 — text-brand-800 dark:text-brand-100 puts ink at the ramp position that dark uses for SURFACES.",
      evidence:
        "#1a3053 on #0d1c2b, composited over --card (the row is inside SettingsCard), vs 6.34:1 in light. Corrects the primary reviewer's 1.9:1, which composited over --background — over the real parent it is worse. .dark.beta reproduces it at 1.30:1, so the fix must be ramp-position-based, not hue-based. Same defect: SplitMasterDetail.tsx:155 dark:text-brand-200 on dark:bg-brand-950/20 = 1.04:1, and :156 dark:text-brand-300/80 = 1.34:1 (code-verified only — Split & merge is empty in the captures).",
      fix: "dark:text-brand-800 (12.13:1), or drop the override and use text-foreground on the tint.",
      shots: ["settings-language__dark.png"],
    },
    {
      id: "d-2",
      severity: "blocker",
      category: "Inverted semantic token",
      where: "globals.css:516-517 — consumed at ModelsSection.tsx:189,287 · providers-v2/shared.tsx:42,48,384",
      problem:
        "--destructive is inverted in dark: the .dark block makes --destructive a dark maroon (#82181a) and --destructive-foreground the bright red (#fb2c36), so every use of --destructive AS INK lands at 1.90:1.",
      evidence:
        "Affects the role=\"alert\" 'Unable to load the default LLM' copy, TONE_TEXT.error (HealthLine for invalid-credential / unreachable / invalid-response), TONE_DOT.error (a status dot, needs 3:1), and the Remove-credentials label. Light is fine at 4.76:1 — dark-only. Token-provable; no error state was captured. The same root cause breaks Badge variant=\"destructive\" (bg-destructive + text-destructive-foreground = red on maroon, ~2.6:1) app-wide.",
      fix: "dark:text-destructive-foreground at these sites (5.00:1), or add a --destructive-text token and rewrite the Badge destructive variant as tint + foreground ink.",
    },
    {
      id: "d-3",
      severity: "blocker",
      category: "Brand-ramp direction",
      where: "LibraryView.tsx:108 · HomeHeroAnchor.tsx:103 · LibraryView.tsx:185 · library/CommentsBanner.tsx:53 · library/BookDetailDialog.tsx:114 · LanguageSection.tsx:80,86 · AppearanceSection.tsx:93-95 · AppSidebar.tsx:180 · ui/EmptyState.tsx:31",
      problem:
        "Hardcoded text-white on bg-brand-600 is 2.64:1 in dark, because dark --brand-600 is #59a1ff — a LIGHT blue. hover:bg-brand-700 drops it to 1.92:1.",
      evidence:
        "shell-library__dark.png shows it directly: the header Add book overrides Button's tokens with bg-brand-600 text-white (2.64:1) while the sidebar's unmodified <Button> renders dark-on-blue via --primary-foreground (7.46:1) — two 'Add book' buttons in one frame with inverted label polarity. Glyphs at the same 2.64:1: the selected-language check, the selected-theme check pip, the help-popover icon plate. .dark.beta: 2.88:1, same failure.",
      fix: "Delete the text-white/bg-brand-600 overrides and let Button's bg-primary text-primary-foreground do it; for bespoke marks use text-white dark:text-brand-950.",
      shots: ["shell-library__dark.png", "settings-language__dark.png", "settings-appearance__dark.png"],
    },
    {
      id: "d-4",
      severity: "blocker",
      category: "Missing dark: handling",
      where: "NotificationsSection.tsx:158,161,191,195 (+ WindowChrome :43,:60)",
      problem: "The notification position picker is invisible end-to-end in dark — stage, slots, hover and selection all land between 1.00:1 and 1.41:1.",
      evidence:
        "Measured: preview window bg-background vs the page's own bg-background = 1.00:1 · its ring-1 ring-black/5 = 1.00:1 · its border = 1.35:1 (the only thing holding the 740px stage together) · slot border-dashed border-muted-foreground/25 = 1.41:1 · slot fill bg-muted/5 = 1.01:1 · hover bg-brand-500/[0.07] = 1.07:1 · 'Place here' text-muted-foreground/70 = 3.51:1 and opacity-0 until hover · selected slot = pointer-events-none opacity-0, i.e. no focus target and no visible selection · preview rail bg-muted/30 = 1.04:1 · chrome bar bg-muted/60 = 1.09:1.",
      fix: "Give the stage its own surface (dark:bg-card / bg-muted/40); dark:ring-white/10; slot border-border or border-muted-foreground/50 (≥3:1); make the selected slot a visible ring-2 ring-brand-500 instead of opacity-0 so it stays focusable.",
      shots: ["settings-notifications__dark.png"],
    },
    {
      id: "d-5",
      severity: "blocker",
      category: "opacity dimming",
      where: "components/ui/button.tsx:8 — visible at ModelsSection.tsx:53-62 and providers-v2/shared.tsx:396",
      problem: "disabled:opacity-50 on a primary button fails in BOTH themes: 2.70:1 in dark, 1.84:1 in light.",
      evidence: "Compositing the whole button over --card: --primary-foreground @50% on --primary @50%. Both 'Save changes' buttons are in this state in settings-models__dark.png.",
      fix: "An explicit disabled recipe (disabled:bg-muted disabled:text-muted-foreground) instead of blanket opacity.",
      shots: ["settings-models__dark.png", "settings-models__light.png"],
    },
    {
      id: "d-6",
      severity: "major",
      category: "Indicator vs track inversion",
      where: "kit.tsx:32,39 (ViewToggle 1.09:1) · components/ui/segmented-control.tsx:40 (1.17:1) · providers-v2/shared.tsx:286 (AuthModeToggle 1.04:1)",
      problem:
        "Every 'raised pill on recessed track' indicator inverts in dark: the pill is bg-background/bg-card (the DARKEST surfaces) on a lighter bg-muted/bg-secondary track, so selection reads as a hole rather than a chip.",
      evidence:
        "Confirmed in crop-viewtoggle__dark.png, settings-appearance__dark.png (Interface New/Classic) and settings-notifications__dark.png (Off/4s/6s/10s). The labels are fine (--primary on bg-background = 7.46:1) — only the surface cue is lost.",
      fix: "Invert the pair in dark: dark:bg-accent / dark:bg-secondary indicator on a dark:bg-background track.",
      shots: ["crop-viewtoggle__dark.png", "settings-appearance__dark.png", "settings-notifications__dark.png"],
    },
    {
      id: "d-7",
      severity: "major",
      category: "Missing dark: handling",
      where: "components/ui/switch.tsx:14,22 — visible at AppearanceSection.tsx:184 and VariantT3List.tsx:62-67",
      problem: "A disabled Switch's on/off state is unreadable in dark: track @50% vs --card = 1.08:1, thumb vs its own track = 1.10:1. Even enabled-unchecked is 1.23:1.",
      evidence: "settings-appearance__dark.png — the Reduce motion toggle is a ghost; you cannot tell it is off.",
      fix: "dark:data-[state=unchecked]:bg-border (or bg-muted-foreground/40) plus a bordered thumb, and a dedicated disabled fill instead of disabled:opacity-50.",
      shots: ["settings-appearance__dark.png", "settings-providers__dark.png"],
    },
    {
      id: "d-8",
      severity: "major",
      category: "Fixed colors that don't adapt",
      where: "globals.css:40-52 (--color-stage-*) + stage-config.ts:22-36 — live at kit.tsx:94,143,464",
      problem: "The stage palette has no .dark block at all: it is defined once in :root and mirrored as raw hex for inline styles, so nothing adapts.",
      evidence:
        "Inline ${stage.hex}1a tint + color: stage.hex over --card: worst 2.30:1 (export #4338ca), gray 2.53:1, storyboard 3.35:1, extract 3.70:1 (light equivalent: 6.72:1) — these are the icon rows under every cover in shell-home__dark.png / shell-library__dark.png. Bare text-stage-* on card: export 2.42, gray 2.53, storyboard 3.35, extract 3.70, easy-read 4.06, speech 4.07, translate 4.16 — all under 4.5. StageBar done-segment vs bg-muted = 2.13:1 (a state indicator); frontier bg-brand-500/25 ring-brand-500/50 vs bg-muted = 1.21:1. AttentionBadge white on bg-stage-toc = 3.19:1 in BOTH themes at 10.5px bold.",
      fix: "Add a .dark block for --color-stage-* (lighten each to ≥L 0.62 for ink use) plus a --color-stage-*-tint that is dark in dark, and drive the inline styles off var(--color-stage-…) instead of stage.hex.",
      shots: ["shell-home__dark.png", "shell-library__dark.png"],
    },
    {
      id: "d-9",
      severity: "major",
      category: "Text on tint",
      where: "VariantT3List.tsx:37 · providers-v2/shared.tsx:49,487 · kit.tsx:93 · NotificationsSection.tsx:83",
      problem: "text-muted-foreground/40 and bg-muted-foreground/40 land at 1.92:1 over --card — below every threshold.",
      evidence:
        "settings-providers__dark.png: the 11px 'v—' is an all-but-absent glyph, and it is also the only TooltipTrigger for 'Provider version' — an invisible interactive target. Also TONE_DOT.muted / the fetching dot (status indicators), the faded StageIconCircle (the 'not done' half of a progress readout) and the toast body bar. The HomeHeroAnchor/BookDetailDialog '·' separators measure the same but are decorative — exempt.",
      fix: "Solid text-muted-foreground for text (5.93:1) and ≥/60 for indicators.",
      shots: ["settings-providers__dark.png"],
    },
    {
      id: "d-10",
      severity: "major",
      category: "Focus rings",
      where: "AppSidebar.tsx:109 · variants/SettingsSearchBar.tsx:70 · AddBookDialog.tsx:46,90 · AppearanceSection.tsx:83",
      problem: "shadow-[0_0_0_3px_var(--brand-50)] halos are invisible in dark (1.29:1) — dark --brand-50 is #15243c, a surface, not a highlight.",
      evidence:
        "SettingsSearchBar:70 is the FOCUS state of the settings search input. The selected theme card survives only because of its inner 1.5px var(--brand-600) ring at 7.46:1. Other rings measured: ring-brand-500 6.14:1 PASS, ring-ring 7.25:1 PASS, ring-brand-500/60 2.88:1 FAIL, ring-brand-500/50 (kit.tsx:482) 2.34:1 FAIL, ring-ring/40 (segmented-control.tsx:62) 2.12:1 FAIL, AppearanceSection:84 hover var(--brand-300) outline 2.61:1 FAIL.",
      fix: "Use --brand-500/--ring at ≥60% for halos, or dark:shadow-[0_0_0_3px_var(--brand-300)].",
      shots: ["settings-appearance__dark.png"],
    },
    {
      id: "d-11",
      severity: "major",
      category: "Missing dark: handling",
      where: "kit.tsx:242,373,531 · HomeHeroAnchor.tsx:87 · LibraryView.tsx:322 · NotificationsSection.tsx:158",
      problem: "ring-1 ring-black/5 has no dark: counterpart anywhere — a black ring on a near-black page is literally the same luminance (1.00:1).",
      evidence: "In shell-library__dark.png the light-covered books (English Pupil's Book) have no edge at all where the artwork is white. BookDetailDialog.tsx:91 already uses ring-white/25 correctly.",
      fix: "ring-black/5 dark:ring-white/10.",
      shots: ["shell-library__dark.png"],
    },
    {
      id: "d-12",
      severity: "major",
      category: "Missing dark: handling",
      where: "AppSidebar.tsx:129 · variants/SettingsNavList.tsx:31 · AppearanceSection.tsx:84 · SidebarLogo.tsx:29 · ui/EmptyState.tsx:31 · AboutSection.tsx:78 · LibraryEmptyState.tsx:24 · BookDetailDialog.tsx:73",
      problem: "Custom drop-shadows are light-only and never adapt; most are decorative, but AppSidebar.tsx:129's rgba(15,23,42,0.05) 0_0_0_1px is the active nav row's ONLY outline.",
      evidence: "SidebarLogo's rgba(43,127,255,0.42) glow measures 1.81:1 on --sidebar.",
      fix: "Token-based shadow-[0_0_0_1px_var(--border)], or dark:shadow-none for the purely decorative ones.",
    },
    {
      id: "d-13",
      severity: "minor",
      category: "Borders & dividers",
      where: "globals.css:518,532 — worst at kit.tsx:416 · AppearanceSection.tsx:84 · NotificationsSection.tsx:191 · LanguageSection.tsx:81",
      problem:
        "--border is 1.35:1 on --background and 1.31:1 on --card, yet dark leans on it harder than light because --card vs --background is only 1.03:1 and --sidebar vs --background is 1.02:1 — the border is the ONLY thing delimiting every card.",
      evidence: "Not a dark regression per se (light is 1.26:1), but where a border is the sole affordance it should be ≥3:1: the dashed AddBookTile '+' in shell-home__dark.png, the theme-card outline, the notification slots, the unselected language radio.",
      fix: "Raise --border in dark, or use a dedicated --border-strong for sole-affordance edges.",
      shots: ["shell-home__dark.png"],
    },
    {
      id: "d-14",
      severity: "minor",
      category: "Missing dark: handling",
      where: "VariantT3List.tsx:22,77 · ModelsSection.tsx:33,220 · PromptsSection.tsx:81 · LibraryView.tsx:261 · providers-v2/shared.tsx:315",
      problem: "bg-muted/N zone fills vanish against --card in dark (1.02–1.07:1), including the open-row highlight at 1.04:1 — which is a state indicator.",
      evidence: "settings-models__dark.png: TaskChips are bg-background chips on a bg-muted/30 footer = 1.06:1 chip surface, so only their 1.31:1 border shows.",
      fix: "dark:bg-muted/60 or dark:bg-accent for any fill that carries meaning.",
      shots: ["settings-models__dark.png"],
    },
    {
      id: "d-15",
      severity: "minor",
      category: "opacity dimming",
      where: "AboutSection.tsx:43 · VariantT3List.tsx:21,112,140 · providers-v2/ProviderEditor.tsx:99 · components/ui/segmented-control.tsx:64",
      problem: "Several opacity-* dims push body copy below 4.5:1 in dark.",
      evidence:
        "opacity-70 soon tiles → 3.44:1 (the Books folder / Diagnostics copy in settings-about__dark.png) · opacity-75 → 3.82:1 (Ollama's subtitle in settings-providers__dark.png) · opacity-50 'seconds' → 2.34:1 · the disabled Plus glyph → 1.90:1 · opacity-60 → 2.86:1 · text-muted-foreground/60 → 2.74:1. Passing: opacity-70 headings 7.88:1, opacity-75 titles 8.97:1, Pager disabled glyph 3.32:1, outline Button disabled 4.61:1.",
      fix: "Dim the surface/border, not the text — keep disabled copy at solid text-muted-foreground.",
      shots: ["settings-about__dark.png", "settings-providers__dark.png"],
    },
    {
      id: "d-16",
      severity: "minor",
      category: "Text on tint",
      where: "LanguageSection.tsx:52 · handoffs/status.tsx:11-14 + home/SplitsSummaryCard.tsx:58-59 · library/CommentsBanner.tsx:33 · library/BookDetailDialog.tsx:286,136 · library/BookRow.tsx:72 · SplitMasterDetail.tsx:55,68",
      problem: "A cluster of sub-3:1 state cues on tints.",
      evidence:
        "Flag-swatch rings: selected ring-brand-600/40 = 2.12:1, unselected dark:ring-white/15 = 1.59:1, and the ring is what distinguishes them. SegBar adjacent segments 1.53:1 (brand-400 vs brand-300) and bg-brand-200 vs track 1.60:1 (redundant with StatusBadge text, so a redundancy loss). CommentsBanner border-brand-500/25 = 1.32:1 and it is the banner's only outline. BookDetailDialog text-emerald-600 on emerald/12 = 4.42:1 marginal fail; border-stage-toc/30 = 1.53:1. BookRow hover:text-red-600 = 3.90:1. SplitMasterDetail active rail 1.74:1 surface delta, inactive chevron 2.34:1.",
      fix: "≥3:1 for anything that encodes state; add dark:text-emerald-400 for the marginal case.",
      shots: ["settings-language__dark.png"],
    },
    {
      id: "d-17",
      severity: "minor",
      category: "Fixed colors that don't adapt",
      where: "AppearanceSection.tsx:61 + settings/options.ts:23",
      problem: "The Dark and System theme mocks paint #0f172a on a --card of #091018 = 1.07:1, so the preview nearly merges with its own card.",
      evidence: "settings-appearance__dark.png — the Dark card reads only because of the selected brand ring; the System card's dark half nearly disappears. barSoft #334155 on it is 1.72:1.",
      fix: "These are deliberate theme representations so the fills must stay fixed — give the mock its own 1px outline in dark.",
      shots: ["settings-appearance__dark.png"],
    },
    {
      id: "d-18",
      severity: "minor",
      category: "Dead code that would fail if revived",
      where: "kit.tsx:194,201,340,403,436 + LibraryTable/GridCard · AddBookDialog.tsx:49,53,92 · settings/providers.ts:22,29,50",
      problem: "Unreferenced prototype code carries light-only recipes that would fail immediately if wired up.",
      evidence:
        "FrontierChip uses bg-stage-toc-50 / bg-stage-validation-50 — near-WHITE pills (#fffbeb, #ecfdf5) with 3.07:1 / 3.58:1 text, in a dark UI. FilterChips inactive count 3.47:1. AddBookDialog bg-red-100 text-red-600 + bg-white plates (glare on dark). settings/providers.ts light-only tiles are dead — ProvidersSection now renders VariantT3List only.",
      fix: "Delete, or fix before they get wired.",
    },
    {
      id: "d-19",
      severity: "nit",
      category: "Decorative — noted, exempt",
      where: "ui/EmptyState.tsx:24-25 · HomeScreen.tsx:36 · AboutSection.tsx:76 · ui/GhostCover.tsx:9 · ui/Eyebrow.tsx:13 · BookCover.tsx:49-50",
      problem: "Radial rgba(43,127,255,.08–.14) glows measure 1.12–1.15:1 and are doing nothing in dark; the GhostCover border (1.17:1) and Eyebrow rule (2.33:1) are likewise inert.",
      fix: "Exempt as decorative, but consider raising the alpha in dark so the hero keeps its depth.",
    },
    {
      id: "d-20",
      severity: "nit",
      category: "Out of scope — flagged for later",
      where: "screens/home/welcome-full/** and welcome-variants/**",
      problem:
        "Paper-textured light-only prototypes (bg-[oklch(0.9_0.01_85)], bg-white/60, border-[oklch(0.88_0.01_85)]) — internally consistent and deliberately paper-toned, not reachable from the reviewed shells.",
      fix: "Fine as-is, but they will read as glaring white slabs if any of them ships into the dark theme.",
    },
  ],
  cleared: [
    { what: "macOS traffic lights #ff5f57/#febc2e/#28c840 (NotificationsSection.tsx:61-63)", why: "6.06 / 10.74 / 8.13 on the bg-muted/60 chrome — fixed by design and fine." },
    { what: "Provider brand glyphs on their /12 tiles (providerLogos.ts:26-30)", why: "Anthropic #d97757 5.35 · Google #4285f4 4.70 · Azure #0078d4 3.80 · Gemini #1c69ff 3.71 (tightest) — all pass 3:1. The /12 washes themselves (1.11–1.14) are decorative." },
    { what: "Every dark:text-amber-{300,400} 'Soon' copy + its dashed borders", why: "9.70–12.45 for text, 4.55 / 3.49 for the borders, coming-soon dot 5.84 — the dark: variants here are correct." },
    { what: "Badge success / warning dark variants (ui/badge.tsx:19,21)", why: "11.69 / 12.41. The info variant has no dark: counterpart but still passes at 8.11 — brittle, not broken." },
    { what: "bg-brand-50 icon plates + text-brand-600/700 (NotificationsSection:113, AboutSection:45, ModelsSection:153, SettingsResultsList:77)", why: "5.91 / 8.11 — the ramp inversion works FOR these; they are the pattern d-1/d-3 should copy." },
    { what: "text-brand-700 links (shared.tsx:365, ModelsSection:212, kit:482, AppSidebar:129)", why: "8.68–10.25." },
    { what: "Unmodified Button default (ui/button.tsx)", why: "7.46:1 — the correct pattern that the hand-rolled CTAs in d-3 bypass." },
    { what: "ModelsSection violet/indigo tiles (:258,272)", why: "Correct dark:bg-*-500/15 dark:text-*-400 pairs." },
    { what: "About hero white logo plate + version badges (AboutSection.tsx:78,89-101)", why: "19.11 vs card (fixed app-icon plate, by design); 'Up to date' badge 11.69." },
    { what: "Notification toast internals (NotificationsSection.tsx:80,82,89)", why: "emerald check 7.75, bg-foreground/70 title bar 7.92, bg-brand-500 progress bar 5.96 — the toast itself is fine; only its stage is broken (d-4)." },
    { what: "Health tones + dots (shared.tsx:40,41,46,47,486)", why: "emerald/amber text 9.89 / 11.13, dots 7.75 / 8.91, ring-2 ring-card separator 7.75." },
    { what: "7 of 14 text-stage-* on card (stage-config.ts)", why: "toc, glossary, quizzes, sign, captions, validation, sectioning measure 4.67–6.19 and pass; the other 7 are d-8." },
    { what: "Cover scrims and pills (kit.tsx:248,277,380 · BookGridCard.tsx:20)", why: "white on bg-black/60 = 12.60, from-black/70 = 15.06 / 8.10, bg-white/90 + #1a1a1a = 15.59." },
    { what: "Body text on card", why: "--foreground 15.56, --muted-foreground 5.93." },
    { what: "Prompts editor (settings-prompts__dark.png)", why: "CodeMirror themes itself; only the bg-muted/25 aside (1.03:1) is a redesign surface." },
    { what: "AppSidebar.tsx:129 active nav bg-card on bg-sidebar (1.05:1)", why: "Not called a failure: the shots do show a faint lighter rect (WCAG's formula compresses near-black) and the state is carried by text-brand-700 at 9.96:1 — but the intended 'raised card' is gone and its ring is invisible (d-12)." },
  ],
  verdict: [
    "Six token-level fixes collapse ~60 of the ~70 actionable failures: brand-ramp direction (d-1, d-3, d-10), --destructive as ink (d-2), indicator-vs-track inversion (d-6, d-7), a .dark stage palette (d-8), dark:ring-white/10 for every ring-black/5 (d-11), and more separation between --border / bg-muted/N and --card in dark (d-13, d-14).",
    "Adopt one rule and most of this cannot recur: never hand-write a brand ramp step or text-white for ink — use the semantic pair (bg-primary/text-primary-foreground, bg-brand-50/text-brand-700) that already inverts correctly.",
    "The .dark.beta block reproduces every brand finding (white-on-brand-600 = 2.88:1), so fixes must change ramp POSITION, never hue.",
  ],
}
