/* eslint-disable lingui/no-unlocalized-strings -- Internal, English-only review report for the team;
 * this data is rendered by the dev-only /redesign-review route and is never localised. */
import type { Review } from "./types"

export const CONSISTENCY_REVIEW: Review = {
  id: "consistency",
  label: "Consistency",
  title: "Consistency review",
  lead: "Do the redesigned surfaces read as one system, or as four authors sharing a color file?",
  method:
    "All 18 light/dark renders + the two ViewToggle crops, read against globals.css and the full components/redesign tree. Two findings are backed by pixel sampling of the PNGs.",
  findings: [
    {
      id: "c-1",
      severity: "blocker",
      category: "Reuse — structural",
      where: "screens/settings/ui.tsx (used by 1.5 of 7 sections)",
      problem:
        "SettingsCard/SettingRow are only used by AppearanceSection and LanguageSection (which then overrides the padding to p-1.5). Notifications, About, Models and Providers each hand-roll a private card that is structurally the same object.",
      evidence:
        "Private copies: NotificationsSection.tsx:97 ControlTile, AboutSection.tsx:29 DetailTile, ModelsSection.tsx:66 SpecializedCard, VariantT3List.tsx:14 Row + :119. This one gap is the root cause of the 6 card insets, 4 tile-title sizes, 6 icon-tile treatments and 4 section-header patterns below.",
      fix: "Add SettingsTile({icon,title,description,soon,children}) and SettingsSectionHeader({title,hint,action}) to ui.tsx; migrate the four sections onto them and delete the private cards.",
      shots: ["settings-about__light.png", "settings-models__light.png", "settings-providers__light.png"],
    },
    {
      id: "c-2",
      severity: "blocker",
      category: "Color",
      where: "screens/library-full/LibraryView.tsx:108, home/home-full/HomeHeroAnchor.tsx:103",
      problem:
        "Hand-rolled bg-brand-600 text-white primaries fail in dark because the ramp inverts brand-600 to a LIGHT blue — the Button primitive does not have this problem.",
      evidence:
        "Pixel-sampled: sidebar Add book (Button default) = text (4,12,19) on (89,161,255) ≈ 9:1. Header Add book = white on the same blue ≈ 2.1:1. Home 'Continue · Extract' pill ≈ 2.6:1. Both read identically in light, so this only surfaces in the dark shots.",
      fix: "Use <Button> with no color overrides (bg-primary/text-primary-foreground). If the pill shape is wanted, add a pill size to buttonVariants instead of a bespoke element.",
      shots: ["shell-library__dark.png", "shell-home__dark.png"],
    },
    {
      id: "c-3",
      severity: "major",
      category: "Color",
      where: "AppSidebar.tsx:129, screens/settings/SettingsNavList.tsx:31",
      problem:
        "The active nav item's outline is shadow-[…rgba(15,23,42,0.08), 0 0 0 1px rgba(15,23,42,0.05)] — black on black, so the dark active state is carried only by bg-card (0.17) against sidebar (0.13).",
      evidence: "Sampled active row in shell-home__dark.png: darkest pixel (9,16,24) — the ring contributes nothing. Crisp hairline in the light shot.",
      fix: "bg-card ring-1 ring-border shadow-sm.",
      shots: ["shell-home__dark.png", "shell-home__light.png"],
    },
    {
      id: "c-4",
      severity: "major",
      category: "Color",
      where: "8 sites: ui/EmptyState.tsx:24,25,31 · HomeScreen.tsx:36 · AboutSection.tsx:76,78 · AppearanceSection.tsx:83,84 · SidebarLogo.tsx:29 · LibraryEmptyState.tsx:24",
      problem:
        "rgba(43,127,255,…) is a frozen copy of light-mode --brand-600. It tracks neither .dark nor .beta (which swaps the hue to purple — the glow would stay blue).",
      fix: "color-mix(in oklch, var(--brand-600) 12%, transparent), or add a --brand-glow var set in both blocks.",
    },
    {
      id: "c-5",
      severity: "major",
      category: "Color",
      where: "handoffs/SplitMasterDetail.tsx:55,148,156 · LanguageSection.tsx:45",
      problem:
        "5 of the 6 dark:*brand-* overrides fight the inverted ramp. dark:bg-brand-950/20 paints a 20% NEAR-WHITE wash in dark, and dark:text-brand-300/80 (0.45) then sits on it at ~1.4:1. LanguageSection's dark:bg-brand-500/10 is merely redundant.",
      evidence: "Code-only: no handoffs screenshot was captured, so the SplitMasterDetail cases are unverified visually.",
      fix: "Delete every dark: brand override — the ramp already inverts.",
    },
    {
      id: "c-6",
      severity: "major",
      category: "Reuse — structural",
      where: "9 dead duplicates: kit.tsx:227 GridCard, :305 FilterChips, :397 NewBookButton, :426 StatusLabel, :492 LibraryTable · library/BookGridCard.tsx · library/BookRow.tsx · ui/Eyebrow.tsx · ui/StageDiscs.tsx",
      problem:
        "Zero import sites (grep-verified), and each encodes a DIFFERENT card recipe — so 'which card is canonical' has no answer for the next contributor.",
      evidence: "BookGridCard: rounded-2xl + transition-[transform,border-color,box-shadow]. GridCard: rounded-xl + hover gradient.",
      fix: "Delete all 9; keep ShelfCard + StageBar + the live Button.",
    },
    {
      id: "c-7",
      severity: "major",
      category: "Reuse — structural",
      where: "components/ui/segmented-control.tsx vs providers-v2/shared.tsx:283 AuthModeToggle vs kit.tsx:22 ViewToggle",
      problem:
        "Three segmented controls. The two hand-rolls own their track/thumb colors; ViewToggle's bg-background thumb on a bg-muted/60 track reads as a raised white chip in light but a RECESSED darker hole in dark — the opposite reading of 'selected'.",
      evidence: "crop-viewtoggle__light.png vs crop-viewtoggle__dark.png, side by side.",
      fix: "Extend SegmentedControl to accept icon-only + stacked options and delete both hand-rolls — its bg-secondary/bg-background pair inverts correctly.",
      shots: ["crop-viewtoggle__dark.png", "crop-viewtoggle__light.png"],
    },
    {
      id: "c-8",
      severity: "major",
      category: "Reuse — structural",
      where: "kit.tsx:492 LibraryTable vs library-full/LibraryView.tsx:248 TableBody",
      problem: "The same table implemented twice, with two CELL consts (kit:490, LibraryView:246), thumbs at h-11 w-8 rounded vs h-14 w-[42px] rounded-md, and only one sticky header.",
      fix: "One BookTable in kit.tsx.",
    },
    {
      id: "c-9",
      severity: "major",
      category: "Spacing & radii",
      where: "ui.tsx:6 · AboutSection.tsx:43,74 · NotificationsSection.tsx:111 · ModelsSection.tsx:96,152 · VariantT3List.tsx:22,119 · LanguageSection.tsx:30",
      problem:
        "Six distinct insets across nine peer cards: px-[22px] py-1.5 · p-[18px] · p-5 · p-7 · p-1.5 (overriding the shared card) · px-4 py-3.5.",
      evidence: "settings-about__* — the hero inset is visibly ~10px deeper than the four tiles below it; the Health-check card in settings-providers__* sits between the two.",
      fix: "One padding const on the shared primitive (p-[18px]); drop p-5/p-7 and the p-1.5 override (use SettingsCard + a dense prop for Language).",
      shots: ["settings-about__light.png", "settings-providers__light.png"],
    },
    {
      id: "c-10",
      severity: "major",
      category: "Spacing & radii",
      where: "variants/SettingsContent.tsx:7,16 (px-[34px]) · HomeHeroAnchor.tsx:58 (px-10) · LibraryView.tsx:92 (px-8) · HomeScreen.tsx:49 (px-8)",
      problem: "Three page gutters, so the h1 physically jogs when you switch tabs. Home itself uses px-10 populated and px-8 empty.",
      evidence: "Measured: Home h1 left edge x=411 vs Library x=400 (displayed) = 8 CSS px of horizontal jog, plus pt-5 vs pt-1 vertically (title y=55 vs y=72). Both themes.",
      fix: "One shell gutter applied by RedesignLayout, not per screen.",
      shots: ["shell-home__light.png", "shell-library__light.png"],
    },
    {
      id: "c-11",
      severity: "major",
      category: "Typography",
      where: "25 distinct text-[Npx] values app-wide (12 in settings), including 5 sub-pixel pairs",
      problem:
        "9/9.5, 10/10.5, 11/11.5, 12/12.5, 13/13.5, 14/14.5 — the 0.5px steps are imperceptible and carry no meaning (SettingsLead 13.5 vs LibraryView:98 12.5 for the same role).",
      fix: "A 7-step scale (11/12/13/14/16/22/26) and delete every half-step.",
    },
    {
      id: "c-12",
      severity: "major",
      category: "Typography",
      where: "ui.tsx:13 (text-2xl) · LibraryView.tsx:95 (text-[22px]) · HomeHeroAnchor.tsx:61 (text-[26px])",
      problem: "Three page-title sizes for three peer screens; Home also uses h2 where the other two use h1.",
      evidence: "'Library' is visibly smaller than 'Good morning' and than 'Appearance'/'About' at identical zoom.",
      fix: "One PageTitle at text-2xl font-bold tracking-[-0.02em], always h1.",
      shots: ["shell-library__light.png", "shell-home__light.png", "settings-about__light.png"],
    },
    {
      id: "c-13",
      severity: "major",
      category: "Typography",
      where: "11 uppercase micro-label recipes (AppearanceSection:135, GroupHeading:8, ModelsSection:121,221, PromptsSection:125, ProviderEditor:123, AboutSection:85, SettingsNavList:18, HomeHeroAnchor:91,115, kit.tsx:451, kit:497/LibraryView:261, LibraryView:198) + unused ui/Eyebrow.tsx as a 12th",
      problem: "Same role, 11 combinations of size (10–12px), weight (medium/semibold/bold) and tracking (.06–.16em).",
      evidence: "shell-home__* shows three in one viewport: 'PICK UP WHERE YOU LEFT OFF' (wide track), \"WHAT'S INSIDE\" (tighter), 'RECENT' (larger, text-foreground).",
      fix: "One <MicroLabel tone=\"muted|strong\"> at 11px/semibold/.08em, used everywhere including the nav group headings.",
      shots: ["shell-home__light.png"],
    },
    {
      id: "c-14",
      severity: "major",
      category: "Icons",
      where: "PromptsSection:132 · AboutSection:45 · NotificationsSection:113 · ModelsSection:98,153 · providers-v2/shared.tsx:148 · SettingsResultsList:77",
      problem:
        "Six brand icon-tile treatments in Settings alone: size-6/rounded-md/14px glyph · size-8/rounded-[10px]/17 · size-9/rounded-[11px]/18 · size-10/rounded-[11px]/19 · size-9/rounded-xl/52% · rounded-md.",
      evidence: "Visible across settings-about__* (32px), settings-notifications__* (36px), settings-models__* (40px), settings-providers__* (36px, rounder).",
      fix: "Two sizes only: size-9 rounded-[10px] [&>svg]:size-[18px] for tiles, size-6 rounded-md [&>svg]:size-3.5 inline.",
      shots: ["settings-about__light.png", "settings-notifications__light.png", "settings-models__light.png"],
    },
    {
      id: "c-15",
      severity: "major",
      category: "Motion",
      where: "components/ui/segmented-control.tsx:38",
      problem:
        "The shared primitive is the least-guarded piece: transition-all duration-200, default easing, no motion-reduce — so every section that correctly reuses it inherits an unguarded animation.",
      fix: "transition-[left,width] duration-200 motion-reduce:transition-none + EASE.",
    },
    {
      id: "c-16",
      severity: "major",
      category: "Motion",
      where: "LanguageSection:43,78,86 · ModelsSection:56 (ease-out) vs Appearance/Notifications/About/providers-v2 (custom EASE)",
      problem: "Two easings coexist inside Settings.",
      evidence: "Not visible in static renders — code-level divergence only.",
      fix: "EASE everywhere, or adopt ease-out as the system easing and delete the custom const.",
    },
    {
      id: "c-17",
      severity: "major",
      category: "Patterns",
      where: "AppearanceSection:135 · NotificationsSection:148 · providers-v2/GroupHeading:8 · ModelsSection:240",
      problem:
        "Four sub-section-header patterns across four peer sections: uppercase eyebrow only · sentence-case bold + right-aligned helper on one line · uppercase eyebrow + helper beneath · h2 bold + helper + right-aligned Save.",
      fix: "One SettingsSectionHeader({title,hint,action}): uppercase micro-label + optional hint below + optional right-side action.",
      shots: ["settings-appearance__light.png", "settings-notifications__light.png", "settings-providers__light.png", "settings-models__light.png"],
    },
    {
      id: "c-18",
      severity: "major",
      category: "Color",
      where: "providers-v2/shared.tsx:530,565,574 · ModelsSection.tsx:197 · VariantT3List.tsx:26",
      problem:
        "Five amber 'soon' recipes, two of them visible on one screen: dashed SOON pin (text-amber-600) · solid + bg-amber-500/10 (text-amber-700) · dashed banner + bg-amber-500/5 · border-amber-500/30 strip · bg-amber-400/70 dot.",
      evidence: "settings-providers__* shows the dashed SOON pin (toolbar + Health check) beside Ollama's solid 'Coming soon' badge.",
      fix: "One <SoonBadge size> + one --warning/--warning-surface token pair. Badge already has a warning variant — use it.",
      shots: ["settings-providers__light.png", "settings-providers__dark.png"],
    },
    {
      id: "c-19",
      severity: "major",
      category: "Reuse — structural",
      where: "4 primary-button recipes: AppSidebar:101 (Button) · LibraryView:108 (Button + color override) · HomeHeroAnchor:103 (raw pill) · kit.tsx:403 (raw, dead)",
      problem: "The same CTA role has four implementations, two of which break in dark (see finding 2).",
      fix: "Button only.",
    },
    {
      id: "c-20",
      severity: "minor",
      category: "Color",
      where: "AboutSection.tsx:78",
      problem: "bg-white logo plaque reads as a bright white block in dark, and the identical mark in SidebarLogo has no plaque at all.",
      fix: "bg-card, or drop the plaque to match SidebarLogo.",
      shots: ["settings-about__dark.png"],
    },
    {
      id: "c-21",
      severity: "minor",
      category: "Color",
      where: "ModelsSection.tsx:258,272",
      problem: "Violet/indigo icon tiles are the only non-brand tinted tiles in Settings (peers all use bg-brand-50 text-brand-600), and they are not tokenized.",
      fix: "Brand tint, or promote real --accent-image/--accent-speech tokens if the color coding is intentional.",
      shots: ["settings-models__light.png", "settings-notifications__light.png"],
    },
    {
      id: "c-22",
      severity: "minor",
      category: "Spacing & radii",
      where: "PromptsSection.tsx:68 (rounded-xl) · NotificationsSection.tsx:158 (rounded-xl) · HomeHeroAnchor.tsx:80 (rounded-3xl) vs 43× rounded-2xl",
      problem: "Three radii for peer containers (12/16/24px).",
      evidence: "The notification preview frame reads tighter-cornered than the tiles directly beneath it.",
      fix: "rounded-2xl for every content card.",
      shots: ["settings-notifications__light.png"],
    },
    {
      id: "c-23",
      severity: "minor",
      category: "Spacing & radii",
      where: "PromptsSection:132 (rounded-md) · AboutSection:45 (rounded-[10px]) · NotificationsSection:113 + ModelsSection:98,153 (rounded-[11px]) · shared.tsx:148 (rounded-xl) · AboutSection:78 (rounded-[20px])",
      problem: "Five icon-tile radii.",
      fix: "rounded-[10px] for all 32–36px tiles.",
    },
    {
      id: "c-24",
      severity: "minor",
      category: "Reuse — structural",
      where: "VariantT3List.tsx:57,106,112",
      problem:
        "Raw <button className=\"grid size-7 place-items-center rounded-md …\"> icon buttons (the disabled + at :112 fakes disabled with opacity-40) while shared.tsx:244 correctly uses Button variant=\"ghost\" size=\"icon\".",
      evidence: "settings-providers__* — the refresh/+ pair floats with no shared hit-area or border, unlike every other control on the page.",
      fix: "Button variant=\"ghost\" size=\"icon\" + real disabled.",
      shots: ["settings-providers__light.png"],
    },
    {
      id: "c-25",
      severity: "minor",
      category: "Reuse — structural",
      where: "EASE declared 4× (AboutSection:15, NotificationsSection:15, AppearanceSection:14, shared.tsx:30) + 9 inline cubic-bezier literals",
      problem: "The system easing is copy-pasted rather than imported.",
      fix: "Export one EASE from components/redesign/motion.ts.",
    },
    {
      id: "c-26",
      severity: "minor",
      category: "Typography",
      where: "AboutSection:48 (text-[13px]) · NotificationsSection:116 (text-[13.5px]) · ModelsSection:102 + VariantT3List:32 (text-sm/14px)",
      problem: "Three sizes for structurally identical tile titles.",
      evidence: "The Models titles read a step larger than About's 'Platform'.",
      fix: "text-sm font-semibold.",
      shots: ["settings-about__light.png", "settings-models__light.png"],
    },
    {
      id: "c-27",
      severity: "minor",
      category: "Icons",
      where: "AppSidebar:133,157,171 (size-[17px]) · :111 (size-[15px]) · MenuRow:69,:194 (size-4)",
      problem: "Three icon sizes inside one sidebar.",
      fix: "Pick one per role and apply it to SettingsRailFooter:27 too.",
    },
    {
      id: "c-28",
      severity: "minor",
      category: "Patterns",
      where: "LanguageSection:78 vs AppearanceSection:95",
      problem: "Two selection affordances for the same 'pick one' job: Language shows an empty radio ring for unselected rows; Appearance hides the mark entirely (opacity-0).",
      evidence: "settings-language__light (5 visible rings) vs settings-appearance__light (no marks on Dark/System).",
      fix: "Visible-ring for both — it is the more discoverable, and it also fixes the invisible Notifications slots.",
      shots: ["settings-language__light.png", "settings-appearance__light.png"],
    },
    {
      id: "c-29",
      severity: "minor",
      category: "Patterns",
      where: "ModelsSection:220 vs ModelsSection:120",
      problem: "The same 'used by N tasks' block gets a shaded bg-muted/30 footer on the top card and a plain border-t on the peer cards.",
      fix: "One treatment via the shared tile.",
      shots: ["settings-models__light.png"],
    },
    {
      id: "c-30",
      severity: "minor",
      category: "Patterns",
      where: "AppearanceSection reduce-motion (Switch) vs NotificationsSection 'Play a sound' (2-option SegmentedControl)",
      problem: "One boolean, two controls.",
      fix: "Switch for booleans, SegmentedControl for 3+ enumerations — which correctly leaves Auto-dismiss segmented.",
      shots: ["settings-appearance__light.png", "settings-notifications__light.png"],
    },
    {
      id: "c-31",
      severity: "minor",
      category: "Patterns",
      where: "AppSidebar:101 + LibraryView:108",
      problem: "Two identical blue 'Add book' CTAs on screen simultaneously, 1400px apart.",
      fix: "Make the header one variant=\"outline\", or drop it — the sidebar one is always visible.",
      shots: ["shell-library__light.png", "shell-library__dark.png"],
    },
    {
      id: "c-32",
      severity: "minor",
      category: "Patterns",
      where: "BookCover.tsx:39 + fit prop usage (kit:377, LibraryView:323 pass fit=\"cover\"; kit:246, kit:532, SplitMasterDetail:59,92 use the contain default)",
      problem:
        "Cover fit differs by call site, and the <img> background is var(--muted) — 0.97 in light, 0.23 in dark — so any letterboxing becomes a visible dark band only in dark.",
      evidence: "The Recent-row band in shell-home__dark.png is partly a lazy-load capture artifact (re-capture showed covers filling), so treat the band as suspected; the token choice is certain.",
      fix: "One fit per context and background: var(--card).",
      shots: ["shell-home__dark.png"],
    },
    {
      id: "c-33",
      severity: "minor",
      category: "Motion",
      where: "kit.tsx:373 ([&_img]:duration-500) · AppearanceSection:71 (duration-500)",
      problem: "Two animations exceed the ≤300ms interaction bar; the entrance is defensible, the hover cover-zoom is not.",
      fix: "duration-300 for the hover zoom.",
    },
    {
      id: "c-34",
      severity: "nit",
      category: "Spacing & radii",
      where: "AppearanceSection.tsx:138",
      problem: "gap-3.5 on the theme-card grid vs gap-3 on the About/Notifications/Models tile grids (14px vs 12px between peer grids).",
      fix: "gap-3.",
    },
    {
      id: "c-35",
      severity: "nit",
      category: "Typography",
      where: "ui.tsx:17 + HomeHeroAnchor:62 (text-[13.5px]) vs LibraryView:98 (text-[12.5px])",
      problem: "Two lead sizes for the same role.",
      fix: "One lead size.",
    },
    {
      id: "c-36",
      severity: "nit",
      category: "Icons",
      where: "kit.tsx:96 (strokeWidth={2}) · kit.tsx:113 (strokeWidth={2.5})",
      problem: "The only explicit stroke overrides in the redesign; the 2.5 check reads heavier than every other check glyph.",
      evidence: "Compare the green check on 'Hyena and Raven' with the 'Up to date' check in settings-about__light.png.",
      fix: "Drop both overrides.",
      shots: ["shell-library__light.png", "settings-about__light.png"],
    },
    {
      id: "c-37",
      severity: "nit",
      category: "Icons",
      where: "kit.tsx:386",
      problem: "Pin … fill-current is the only filled lucide glyph in the redesign.",
      fix: "Acceptable as a 'pinned' semantic — document it as the exception.",
    },
    {
      id: "c-38",
      severity: "nit",
      category: "Patterns",
      where: "AboutSection.tsx:126-132",
      problem: "The Platform tile has ~90px of dead space because it shares a stretch row with Onboarding tour, which has a button.",
      fix: "items-start on the grid, or a min-h for short tiles.",
      shots: ["settings-about__light.png", "settings-about__dark.png"],
    },
    {
      id: "c-39",
      severity: "nit",
      category: "Motion",
      where: "AppearanceSection.tsx:93",
      problem: "transition-all duration-200 on the check chip has no motion-reduce guard while its sibling at :71 does.",
      fix: "Add motion-reduce:transition-none.",
    },
  ],
  cleared: [
    { what: "Icon set", why: "lucide throughout the redesign — no mixing with another set." },
    {
      what: "BookCover.tsx:49-50 #eef0f2/#b6bcc6 placeholder plate",
      why: "A light-grey card in dark, but no placeholder covers appear in any captured shot — code-only, downgraded.",
    },
    { what: "ring-black/5 on covers (5 uses)", why: "Invisible in dark but harmless; ring-border is the token fix, not a defect." },
  ],
  verdict: [
    "Make screens/settings/ui.tsx mandatory and complete — add SettingsTile + SettingsSectionHeader and migrate the four private cards. Collapses 6 card insets → 1, 4 tile-title sizes → 1, 6 icon-tile treatments → 2, 4 section-header patterns → 1.",
    "Land a type scale and one MicroLabel — 25 arbitrary text-[Npx] values → ~7 steps (kill every half-step), 11 uppercase recipes → 1 component. Most visible change to anyone flipping between Home, Library and Settings.",
    "Ban raw color in the redesign tree — route every primary CTA through Button (fixes the 2.6:1 dark CTA), swap the two rgba(15,23,42,…) active-nav shadows for ring-1 ring-border, tokenize the 8 rgba(43,127,255,…) glows, delete all 5 dark:*brand-* overrides.",
  ],
}
