import { memo, useEffect, useRef } from "react"
import { Eye, EyeOff, Maximize2, Pencil } from "lucide-react"
import { BASE_URL } from "@/api/client"
import { Trans, useLingui } from "@lingui/react/macro"
import type { CaptionEdit, CaptionEntry, LightboxEntry } from "../lib/types"

interface CaptionCardProps {
  bookLabel: string
  cap: CaptionEntry
  list: CaptionEntry[]
  editing: CaptionEdit | null
  onStartEdit: (cap: CaptionEntry) => void
  onChangeDraft: (value: string) => void
  onCommitEdit: () => void
  onCancelEdit: () => void
  onToggleDecorative: (imageId: string) => void
  onOpenLightbox: (entries: LightboxEntry[], index: number) => void
  pageId: string
  pageNumber: number
}

export const CaptionCard = memo(function CaptionCard({
  bookLabel,
  cap,
  list,
  editing,
  onStartEdit,
  onChangeDraft,
  onCommitEdit,
  onCancelEdit,
  onToggleDecorative,
  onOpenLightbox,
  pageId,
  pageNumber,
}: CaptionCardProps) {
  const { t } = useLingui()
  const isDecorative = cap.decorative === true
  const isManual = cap.source === "manual"
  const isEditing = editing?.imageId === cap.imageId
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus()
      const len = textareaRef.current.value.length
      textareaRef.current.setSelectionRange(len, len)
    }
  }, [isEditing])

  useEffect(() => {
    const el = textareaRef.current
    if (!isEditing || !el) return
    el.style.height = "auto"
    el.style.height = `${el.scrollHeight + 2}px`
  }, [isEditing, editing?.draft])

  const openLightbox = () => {
    const entries: LightboxEntry[] = list.map((c) => ({ cap: c, pageId, pageNumber }))
    const idx = list.findIndex((c) => c.imageId === cap.imageId)
    onOpenLightbox(entries, Math.max(0, idx))
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Escape") {
      e.preventDefault()
      onCancelEdit()
    } else if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
      e.preventDefault()
      onCommitEdit()
    }
  }

  return (
    <div className="group/card relative flex flex-col rounded-xl border border-border/70 bg-card overflow-hidden transition-all duration-200 hover:shadow-md hover:-translate-y-0.5">
      <button
        type="button"
        onClick={openLightbox}
        aria-label={t`Open image preview`}
        className="relative block w-full h-56 bg-muted overflow-hidden cursor-zoom-in"
      >
        <img
          src={`${BASE_URL}/books/${bookLabel}/images/${cap.imageId}`}
          alt={isDecorative ? "" : cap.caption}
          aria-hidden={isDecorative || undefined}
          loading="lazy"
          className={`w-full h-full object-contain block transition-transform duration-300 ease-out group-hover/card:scale-[1.02] ${
            isDecorative ? "opacity-80" : ""
          }`}
        />
        {isDecorative && (
          <span className="absolute left-2 top-2 inline-flex items-center gap-1 rounded-md bg-amber-500/95 text-white text-[10px] font-semibold uppercase tracking-wider px-1.5 py-0.5 shadow-sm">
            <EyeOff className="h-2.5 w-2.5" />
            <Trans>Decorative</Trans>
          </span>
        )}
        <span
          aria-hidden
          className="absolute right-2 top-2 inline-flex items-center justify-center h-7 w-7 rounded-full bg-black/55 text-white opacity-0 group-hover/card:opacity-100 transition-opacity duration-200 backdrop-blur-sm pointer-events-none"
        >
          <Maximize2 className="h-3.5 w-3.5" />
        </span>
      </button>

      <div className="flex flex-1 flex-col gap-1.5 p-3">
        <div className="flex items-center gap-1.5">
          <span className="inline-flex items-center gap-1.5 font-mono text-[10px] font-semibold tracking-wide text-teal-700/90 bg-teal-50 rounded px-1.5 py-0.5">
            <span
              aria-hidden
              className={`h-1.5 w-1.5 rounded-full ${isManual ? "bg-emerald-500" : "bg-violet-400"}`}
              title={isManual ? t`Edited manually` : t`Generated by AI`}
            />
            {cap.imageId}
          </span>
          <button
            type="button"
            onClick={() => onToggleDecorative(cap.imageId)}
            aria-pressed={isDecorative}
            title={
              isDecorative
                ? t`This image is marked decorative — click to un-mark`
                : t`Mark as decorative (hidden from screen readers)`
            }
            className={`ml-auto inline-flex h-6 items-center gap-1 rounded-md px-1.5 text-[11px] font-medium transition-all duration-200 cursor-pointer ${
              isDecorative
                ? "bg-amber-100 text-amber-700 hover:bg-amber-200"
                : "text-muted-foreground/70 hover:text-foreground hover:bg-muted opacity-70 group-hover/card:opacity-100 focus-visible:opacity-100"
            }`}
          >
            {isDecorative ? <EyeOff className="h-3 w-3" /> : <Eye className="h-3 w-3" />}
            <span>{t`Decorative`}</span>
          </button>
        </div>

        {isDecorative ? (
          <p className="flex-1 text-[12px] leading-relaxed text-amber-700/90 italic">
            <Trans>Hidden from screen readers, no caption needed.</Trans>
          </p>
        ) : isEditing ? (
          <div className="relative flex flex-col">
            <textarea
              ref={textareaRef}
              value={editing!.draft}
              onChange={(e) => onChangeDraft(e.target.value)}
              onKeyDown={handleKeyDown}
              aria-label={t`Caption for ${cap.imageId}`}
              placeholder={t`Describe this image…`}
              className="w-full min-h-[72px] resize-none overflow-hidden rounded-md border border-teal-400 bg-background p-2.5 pb-9 text-[13px] leading-relaxed text-foreground focus:outline-none focus:ring-2 focus:ring-teal-200 transition-colors duration-150"
              rows={3}
            />
            <div className="absolute bottom-1.5 right-1.5 flex items-center gap-1.5">
              <button
                type="button"
                onClick={onCancelEdit}
                className="text-[11px] font-medium rounded-md px-2 py-0.5 bg-background/80 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors cursor-pointer backdrop-blur-sm"
              >
                {t`Cancel`}
              </button>
              <button
                type="button"
                onClick={onCommitEdit}
                className="text-[11px] font-medium rounded-md px-2 py-0.5 bg-teal-600 text-white hover:bg-teal-500 transition-colors cursor-pointer shadow-sm"
              >
                {t`Done`}
              </button>
            </div>
          </div>
        ) : (
          <button
            type="button"
            onClick={() => onStartEdit(cap)}
            className={`group/cap relative flex min-h-[72px] flex-col text-left rounded-md border border-dashed border-border/60 bg-background/40 p-2.5 pb-9 transition-colors duration-150 hover:border-teal-300 hover:bg-teal-50/40 focus-visible:border-teal-300 focus-visible:bg-teal-50/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-200 cursor-text ${
              cap.caption ? "" : "text-muted-foreground/70 italic"
            }`}
            title={t`Click to edit caption`}
          >
            <span className="block text-[13px] leading-relaxed text-foreground">
              {cap.caption || t`Add caption…`}
            </span>
            <span className="absolute bottom-1.5 right-1.5 inline-flex items-center gap-1 rounded px-1 py-0.5 text-[10px] font-medium text-teal-600 opacity-60 transition-opacity duration-150 group-hover/cap:opacity-100 group-focus-visible/cap:opacity-100">
              <Pencil className="h-3 w-3" />
              <span>{t`Edit`}</span>
            </span>
          </button>
        )}
      </div>
    </div>
  )
})
