openai:
  default: alloy
  af: coral
  am: coral
  ar: coral
  bn: coral
  cs: coral
  da: coral
  de: coral
  el: coral
  en: alloy
  es: coral
  es-ar: coral
  es-es: coral
  es-mx: coral
  es-uy: coral
  fa: coral
  fi: coral
  fil: coral
  fr: coral
  fr-ca: coral
  he: coral
  hi: coral
  hu: coral
  id: coral
  it: coral
  ja: coral
  ko: coral
  ms: coral
  nl: coral
  'no': coral
  np: coral
  pl: coral
  pt: coral
  pt-br: coral
  ro: coral
  ru: coral
  si: coral
  sv: coral
  sw: coral
  sw-ke: coral
  sw-tz: coral
  ta: coral
  te: coral
  th: coral
  tr: coral
  uk: coral
  ur: coral
  vi: coral
  zh: coral
  zu: coral
azure:
  default: en-US-JennyNeural
  af: af-ZA-AdriNeural
  am: am-ET-MekdesNeural
  ar: ar-SA-ZariyahNeural
  bn: bn-IN-TanishaaNeural
  cs: cs-CZ-VlastaNeural
  da: da-DK-ChristelNeural
  de: de-DE-KatjaNeural
  el: el-GR-AthinaNeural
  en: en-US-JennyNeural
  en-tz: en-US-JennyNeural
  es: es-MX-DaliaNeural
  es-ar: es-AR-ElenaNeural
  es-es: es-ES-ElviraNeural
  es-mx: es-MX-DaliaNeural
  es-uy: es-UY-ValentinaNeural
  fa: fa-IR-DilaraNeural
  fi: fi-FI-NooraNeural
  fil: fil-PH-BlessicaNeural
  fr: fr-FR-DeniseNeural
  fr-ca: fr-CA-SylvieNeural
  he: he-IL-HilaNeural
  hi: hi-IN-SwaraNeural
  hu: hu-HU-NoemiNeural
  id: id-ID-GadisNeural
  it: it-IT-ElsaNeural
  ja: ja-JP-NanamiNeural
  ko: ko-KR-SunHiNeural
  ms: ms-MY-YasminNeural
  ne: ne-NP-HemkalaNeural
  nl: nl-NL-ColetteNeural
  'no': nb-NO-PernilleNeural
  np: ne-NP-HemkalaNeural
  pl: pl-PL-AgnieszkaNeural
  pt: pt-PT-RaquelNeural
  pt-br: pt-BR-FranciscaNeural
  ro: ro-RO-AlinaNeural
  ru: ru-RU-SvetlanaNeural
  si: si-LK-ThiliniNeural
  sv: sv-SE-SofieNeural
  sw: sw-KE-ZuriNeural
  sw-ke: sw-KE-ZuriNeural
  sw-tz: sw-TZ-RehemaNeural
  ta: ta-IN-PallaviNeural
  te: te-IN-ShrutiNeural
  th: th-TH-PremwadeeNeural
  tr: tr-TR-EmelNeural
  uk: uk-UA-PolinaNeural
  ur: ur-PK-UzmaNeural
  vi: vi-VN-HoaiMyNeural
  zh: zh-CN-XiaoxiaoNeural
  zu: zu-ZA-ThandoNeural
gemini:
  ne: Kore
  si: Aoede
  sq: Kore
  ur: Kore
