import { createFileRoute } from "@tanstack/react-router"
import { useState } from "react"
import { Trans, useLingui } from "@lingui/react/macro"
import { Copy, UsersRound } from "lucide-react"
import { StudioTopBar } from "@/components/StudioTopBar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { classroomApi, classroomConfigured, type ClassroomMaterial, type ClassroomSession } from "@/api/classroom-client"

export const Route = createFileRoute("/classroom-sessions")({ component: ClassroomSessionsPage })
const storedTeacher = () => typeof window === "undefined" ? "" : window.localStorage.getItem("adt.classroom.teacherId") ?? ""
function ClassroomSessionsPage() {
  const { t } = useLingui(); const [teacherId, setTeacherId] = useState(storedTeacher); const [materials, setMaterials] = useState<ClassroomMaterial[]>([]); const [materialId, setMaterialId] = useState(""); const [duration, setDuration] = useState(120); const [session, setSession] = useState<ClassroomSession | null>(null); const [error, setError] = useState("")
  const load = async () => { try { setError(""); window.localStorage.setItem("adt.classroom.teacherId", teacherId); const data = await classroomApi.materials(teacherId); setMaterials(data); setMaterialId(data[0]?.id ?? "") } catch (cause) { setError(cause instanceof Error ? cause.message : t`Unable to load materials`) } }
  const create = async () => { try { setError(""); setSession(await classroomApi.createSession(teacherId, materialId, duration)) } catch (cause) { setError(cause instanceof Error ? cause.message : t`Unable to create session`) } }
  if (!classroomConfigured()) return <div className="flex min-h-0 flex-1 flex-col"><StudioTopBar brandLinksHome trailingTitle={<Trans>Classroom sessions</Trans>} /><main className="mx-auto w-full max-w-2xl space-y-4 p-6"><h1 className="text-2xl font-semibold"><Trans>Classroom sessions</Trans></h1><p className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground"><Trans>Connect the Classroom Worker by setting VITE_CLASSROOM_API_URL, then restart Studio. For local development, use the URL printed by wrangler dev.</Trans></p></main></div>
  return <div className="flex min-h-0 flex-1 flex-col"><StudioTopBar brandLinksHome trailingTitle={<Trans>Classroom sessions</Trans>} /><main className="mx-auto w-full max-w-2xl space-y-6 overflow-auto p-6"><div><h1 className="text-2xl font-semibold"><Trans>Start a classroom session</Trans></h1><p className="text-sm text-muted-foreground"><Trans>Create a temporary join code for one of your saved materials.</Trans></p></div><div className="space-y-2"><Label htmlFor="teacher-id"><Trans>Teacher ID</Trans></Label><div className="flex gap-2"><Input id="teacher-id" value={teacherId} onChange={(event) => setTeacherId(event.target.value)} placeholder={t`Your teacher identifier`} /><Button disabled={!teacherId} onClick={load}><Trans>Load materials</Trans></Button></div></div>{materials.length > 0 && <div className="space-y-4 rounded-lg border p-5"><div className="space-y-2"><Label htmlFor="session-material"><Trans>Material</Trans></Label><select id="session-material" className="h-9 w-full rounded-md border bg-background px-3" value={materialId} onChange={(event) => setMaterialId(event.target.value)}>{materials.map((material) => <option key={material.id} value={material.id}>{material.title}</option>)}</select></div><div className="space-y-2"><Label htmlFor="session-duration"><Trans>Session duration in minutes</Trans></Label><Input id="session-duration" type="number" min="5" max="1440" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></div><Button disabled={!materialId} onClick={create}><UsersRound className="mr-2 h-4 w-4" /><Trans>Create session</Trans></Button></div>}{session && <section className="rounded-lg border border-primary/30 bg-primary/5 p-5"><h2 className="font-semibold"><Trans>Session ready</Trans></h2><p className="mt-3 text-sm"><Trans>Join code</Trans></p><p className="text-3xl font-bold tracking-[0.3em]">{session.joinCode}</p><p className="mt-3 break-all text-sm text-muted-foreground">{session.shareUrl}</p><Button className="mt-3" variant="outline" onClick={() => navigator.clipboard.writeText(session.shareUrl)}><Copy className="mr-2 h-4 w-4" /><Trans>Copy join link</Trans></Button></section>}{error && <p className="text-sm text-destructive">{error}</p>}</main></div>
}
