import { createFileRoute } from "@tanstack/react-router"
import { useQuery } from "@tanstack/react-query"
import { Trans } from "@lingui/react/macro"
import { StudioTopBar } from "@/components/StudioTopBar"
import { classroomApi } from "@/api/classroom-client"
import { getWorkspace } from "@/features/workspace/config"

export const Route = createFileRoute("/workspace/")({ component: WorkspaceDashboard })
function WorkspaceDashboard() { const workspace = getWorkspace(); const analytics = useQuery({ queryKey: ["workspace-analytics", workspace?.teacherId], queryFn: () => classroomApi.analytics(workspace!.teacherId), enabled: !!workspace }); if (!workspace) return <div className="flex min-h-screen items-center justify-center"><Trans>Connect a workspace before viewing analytics.</Trans></div>; const data = analytics.data; return <div className="flex min-h-0 flex-1 flex-col"><StudioTopBar brandLinksHome trailingTitle={<Trans>Teacher workspace</Trans>} /><main className="mx-auto w-full max-w-6xl space-y-6 overflow-auto p-6"><div><h1 className="text-2xl font-semibold"><Trans>Teacher workspace</Trans></h1><p className="text-sm text-muted-foreground"><Trans>Cloud synchronization, parent delivery, and recent activity.</Trans></p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Card label={<Trans>Profiles created</Trans>} value={data?.totalProfiles ?? 0} /><Card label={<Trans>Materials generated</Trans>} value={data?.totalMaterials ?? 0} /><Card label={<Trans>Materials sent</Trans>} value={data?.totalMaterialsSent ?? 0} /><Card label={<Trans>Materials synced</Trans>} value={data?.totalMaterialsSynced ?? 0} /><Card label={<Trans>Pending uploads</Trans>} value={data?.pendingUploads ?? 0} /></div><section className="rounded-lg border p-5"><h2 className="font-semibold"><Trans>Recent activity</Trans></h2>{analytics.isLoading ? <p className="mt-3 text-sm text-muted-foreground"><Trans>Loading activity…</Trans></p> : <ul className="mt-3 space-y-3">{data?.activity.map((event, index) => <li key={`${event.created_at}-${index}`} className="border-b pb-3 text-sm last:border-0"><p>{event.description}</p><p className="text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString()}</p></li>)}{data?.activity.length === 0 && <li className="text-sm text-muted-foreground"><Trans>No workspace activity yet.</Trans></li>}</ul>}</section></main></div> }
function Card({ label, value }: { label: React.ReactNode; value: number }) { return <section className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></section> }
