/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BooksNewRouteImport } from "./routes/books.new"
import { Route as BooksLabelRouteImport } from "./routes/books.$label"
import { Route as BooksLabelIndexRouteImport } from "./routes/books.$label.index"
import { Route as BooksLabelDebugRouteImport } from "./routes/books.$label.debug"
import { Route as BooksLabelStepRouteImport } from "./routes/books.$label.$step"
import { Route as BooksLabelStepIndexRouteImport } from "./routes/books.$label.$step.index"
import { Route as BooksLabelStepSettingsRouteImport } from "./routes/books.$label.$step.settings"
import { Route as BooksLabelStepPageIdRouteImport } from "./routes/books.$label.$step.$pageId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: "/books/new",
  path: "/books/new",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksLabelRoute = BooksLabelRouteImport.update({
  id: "/books/$label",
  path: "/books/$label",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksLabelIndexRoute = BooksLabelIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BooksLabelRoute,
} as any)
const BooksLabelDebugRoute = BooksLabelDebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => BooksLabelRoute,
} as any)
const BooksLabelStepRoute = BooksLabelStepRouteImport.update({
  id: "/$step",
  path: "/$step",
  getParentRoute: () => BooksLabelRoute,
} as any)
const BooksLabelStepIndexRoute = BooksLabelStepIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BooksLabelStepRoute,
} as any)
const BooksLabelStepSettingsRoute = BooksLabelStepSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => BooksLabelStepRoute,
} as any)
const BooksLabelStepPageIdRoute = BooksLabelStepPageIdRouteImport.update({
  id: "/$pageId",
  path: "/$pageId",
  getParentRoute: () => BooksLabelStepRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/books/$label": typeof BooksLabelRouteWithChildren
  "/books/new": typeof BooksNewRoute
  "/books/$label/$step": typeof BooksLabelStepRouteWithChildren
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/books/$label/": typeof BooksLabelIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step/": typeof BooksLabelStepIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/books/new": typeof BooksNewRoute
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/books/$label": typeof BooksLabelIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step": typeof BooksLabelStepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/books/$label": typeof BooksLabelRouteWithChildren
  "/books/new": typeof BooksNewRoute
  "/books/$label/$step": typeof BooksLabelStepRouteWithChildren
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/books/$label/": typeof BooksLabelIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step/": typeof BooksLabelStepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/books/$label"
    | "/books/new"
    | "/books/$label/$step"
    | "/books/$label/debug"
    | "/books/$label/"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/books/new"
    | "/books/$label/debug"
    | "/books/$label"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step"
  id:
    | "__root__"
    | "/"
    | "/books/$label"
    | "/books/new"
    | "/books/$label/$step"
    | "/books/$label/debug"
    | "/books/$label/"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksLabelRoute: typeof BooksLabelRouteWithChildren
  BooksNewRoute: typeof BooksNewRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/new": {
      id: "/books/new"
      path: "/books/new"
      fullPath: "/books/new"
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/$label": {
      id: "/books/$label"
      path: "/books/$label"
      fullPath: "/books/$label"
      preLoaderRoute: typeof BooksLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/$label/": {
      id: "/books/$label/"
      path: "/"
      fullPath: "/books/$label/"
      preLoaderRoute: typeof BooksLabelIndexRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/books/$label/debug": {
      id: "/books/$label/debug"
      path: "/debug"
      fullPath: "/books/$label/debug"
      preLoaderRoute: typeof BooksLabelDebugRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/books/$label/$step": {
      id: "/books/$label/$step"
      path: "/$step"
      fullPath: "/books/$label/$step"
      preLoaderRoute: typeof BooksLabelStepRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/books/$label/$step/": {
      id: "/books/$label/$step/"
      path: "/"
      fullPath: "/books/$label/$step/"
      preLoaderRoute: typeof BooksLabelStepIndexRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
    "/books/$label/$step/settings": {
      id: "/books/$label/$step/settings"
      path: "/settings"
      fullPath: "/books/$label/$step/settings"
      preLoaderRoute: typeof BooksLabelStepSettingsRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
    "/books/$label/$step/$pageId": {
      id: "/books/$label/$step/$pageId"
      path: "/$pageId"
      fullPath: "/books/$label/$step/$pageId"
      preLoaderRoute: typeof BooksLabelStepPageIdRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
  }
}

interface BooksLabelStepRouteChildren {
  BooksLabelStepPageIdRoute: typeof BooksLabelStepPageIdRoute
  BooksLabelStepSettingsRoute: typeof BooksLabelStepSettingsRoute
  BooksLabelStepIndexRoute: typeof BooksLabelStepIndexRoute
}

const BooksLabelStepRouteChildren: BooksLabelStepRouteChildren = {
  BooksLabelStepPageIdRoute: BooksLabelStepPageIdRoute,
  BooksLabelStepSettingsRoute: BooksLabelStepSettingsRoute,
  BooksLabelStepIndexRoute: BooksLabelStepIndexRoute,
}

const BooksLabelStepRouteWithChildren = BooksLabelStepRoute._addFileChildren(
  BooksLabelStepRouteChildren,
)

interface BooksLabelRouteChildren {
  BooksLabelStepRoute: typeof BooksLabelStepRouteWithChildren
  BooksLabelDebugRoute: typeof BooksLabelDebugRoute
  BooksLabelIndexRoute: typeof BooksLabelIndexRoute
}

const BooksLabelRouteChildren: BooksLabelRouteChildren = {
  BooksLabelStepRoute: BooksLabelStepRouteWithChildren,
  BooksLabelDebugRoute: BooksLabelDebugRoute,
  BooksLabelIndexRoute: BooksLabelIndexRoute,
}

const BooksLabelRouteWithChildren = BooksLabelRoute._addFileChildren(
  BooksLabelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksLabelRoute: BooksLabelRouteWithChildren,
  BooksNewRoute: BooksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
