/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as RedesignRouteImport } from "./routes/redesign"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as RedesignIndexRouteImport } from "./routes/redesign.index"
import { Route as RedesignSettingsRouteImport } from "./routes/redesign.settings"
import { Route as RedesignLibraryRouteImport } from "./routes/redesign.library"
import { Route as RedesignHandoffsRouteImport } from "./routes/redesign.handoffs"
import { Route as PromptsSettingsRouteImport } from "./routes/prompts.settings"
import { Route as BooksNewRouteImport } from "./routes/books.new"
import { Route as BooksImportRouteImport } from "./routes/books.import"
import { Route as BooksLabelRouteImport } from "./routes/books.$label"
import { Route as RedesignSettingsIndexRouteImport } from "./routes/redesign.settings.index"
import { Route as BooksLabelIndexRouteImport } from "./routes/books.$label.index"
import { Route as RedesignSettingsThemeRouteImport } from "./routes/redesign.settings.theme"
import { Route as RedesignSettingsProvidersRouteImport } from "./routes/redesign.settings.providers"
import { Route as RedesignSettingsNotificationsRouteImport } from "./routes/redesign.settings.notifications"
import { Route as RedesignSettingsLanguageRouteImport } from "./routes/redesign.settings.language"
import { Route as RedesignSettingsAboutRouteImport } from "./routes/redesign.settings.about"
import { Route as BooksLabelDebugRouteImport } from "./routes/books.$label.debug"
import { Route as BooksLabelStepRouteImport } from "./routes/books.$label.$step"
import { Route as BooksLabelStepIndexRouteImport } from "./routes/books.$label.$step.index"
import { Route as BooksLabelStepSettingsRouteImport } from "./routes/books.$label.$step.settings"
import { Route as BooksLabelStepPageIdRouteImport } from "./routes/books.$label.$step.$pageId"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignRoute = RedesignRouteImport.update({
  id: "/redesign",
  path: "/redesign",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignIndexRoute = RedesignIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => RedesignRoute,
} as any)
const RedesignSettingsRoute = RedesignSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => RedesignRoute,
} as any)
const RedesignLibraryRoute = RedesignLibraryRouteImport.update({
  id: "/library",
  path: "/library",
  getParentRoute: () => RedesignRoute,
} as any)
const RedesignHandoffsRoute = RedesignHandoffsRouteImport.update({
  id: "/handoffs",
  path: "/handoffs",
  getParentRoute: () => RedesignRoute,
} as any)
const PromptsSettingsRoute = PromptsSettingsRouteImport.update({
  id: "/prompts/settings",
  path: "/prompts/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: "/books/new",
  path: "/books/new",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksImportRoute = BooksImportRouteImport.update({
  id: "/books/import",
  path: "/books/import",
  getParentRoute: () => rootRouteImport,
} as any)
const BooksLabelRoute = BooksLabelRouteImport.update({
  id: "/books/$label",
  path: "/books/$label",
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignSettingsIndexRoute = RedesignSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => RedesignSettingsRoute,
} as any)
const BooksLabelIndexRoute = BooksLabelIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BooksLabelRoute,
} as any)
const RedesignSettingsThemeRoute = RedesignSettingsThemeRouteImport.update({
  id: "/theme",
  path: "/theme",
  getParentRoute: () => RedesignSettingsRoute,
} as any)
const RedesignSettingsProvidersRoute =
  RedesignSettingsProvidersRouteImport.update({
    id: "/providers",
    path: "/providers",
    getParentRoute: () => RedesignSettingsRoute,
  } as any)
const RedesignSettingsNotificationsRoute =
  RedesignSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => RedesignSettingsRoute,
  } as any)
const RedesignSettingsLanguageRoute =
  RedesignSettingsLanguageRouteImport.update({
    id: "/language",
    path: "/language",
    getParentRoute: () => RedesignSettingsRoute,
  } as any)
const RedesignSettingsAboutRoute = RedesignSettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => RedesignSettingsRoute,
} as any)
const BooksLabelDebugRoute = BooksLabelDebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => BooksLabelRoute,
} as any)
const BooksLabelStepRoute = BooksLabelStepRouteImport.update({
  id: "/$step",
  path: "/$step",
  getParentRoute: () => BooksLabelRoute,
} as any)
const BooksLabelStepIndexRoute = BooksLabelStepIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BooksLabelStepRoute,
} as any)
const BooksLabelStepSettingsRoute = BooksLabelStepSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => BooksLabelStepRoute,
} as any)
const BooksLabelStepPageIdRoute = BooksLabelStepPageIdRouteImport.update({
  id: "/$pageId",
  path: "/$pageId",
  getParentRoute: () => BooksLabelStepRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/redesign": typeof RedesignRouteWithChildren
  "/settings": typeof SettingsRoute
  "/books/$label": typeof BooksLabelRouteWithChildren
  "/books/import": typeof BooksImportRoute
  "/books/new": typeof BooksNewRoute
  "/prompts/settings": typeof PromptsSettingsRoute
  "/redesign/handoffs": typeof RedesignHandoffsRoute
  "/redesign/library": typeof RedesignLibraryRoute
  "/redesign/settings": typeof RedesignSettingsRouteWithChildren
  "/redesign/": typeof RedesignIndexRoute
  "/books/$label/$step": typeof BooksLabelStepRouteWithChildren
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/redesign/settings/about": typeof RedesignSettingsAboutRoute
  "/redesign/settings/language": typeof RedesignSettingsLanguageRoute
  "/redesign/settings/notifications": typeof RedesignSettingsNotificationsRoute
  "/redesign/settings/providers": typeof RedesignSettingsProvidersRoute
  "/redesign/settings/theme": typeof RedesignSettingsThemeRoute
  "/books/$label/": typeof BooksLabelIndexRoute
  "/redesign/settings/": typeof RedesignSettingsIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step/": typeof BooksLabelStepIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/settings": typeof SettingsRoute
  "/books/import": typeof BooksImportRoute
  "/books/new": typeof BooksNewRoute
  "/prompts/settings": typeof PromptsSettingsRoute
  "/redesign/handoffs": typeof RedesignHandoffsRoute
  "/redesign/library": typeof RedesignLibraryRoute
  "/redesign": typeof RedesignIndexRoute
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/redesign/settings/about": typeof RedesignSettingsAboutRoute
  "/redesign/settings/language": typeof RedesignSettingsLanguageRoute
  "/redesign/settings/notifications": typeof RedesignSettingsNotificationsRoute
  "/redesign/settings/providers": typeof RedesignSettingsProvidersRoute
  "/redesign/settings/theme": typeof RedesignSettingsThemeRoute
  "/books/$label": typeof BooksLabelIndexRoute
  "/redesign/settings": typeof RedesignSettingsIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step": typeof BooksLabelStepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/redesign": typeof RedesignRouteWithChildren
  "/settings": typeof SettingsRoute
  "/books/$label": typeof BooksLabelRouteWithChildren
  "/books/import": typeof BooksImportRoute
  "/books/new": typeof BooksNewRoute
  "/prompts/settings": typeof PromptsSettingsRoute
  "/redesign/handoffs": typeof RedesignHandoffsRoute
  "/redesign/library": typeof RedesignLibraryRoute
  "/redesign/settings": typeof RedesignSettingsRouteWithChildren
  "/redesign/": typeof RedesignIndexRoute
  "/books/$label/$step": typeof BooksLabelStepRouteWithChildren
  "/books/$label/debug": typeof BooksLabelDebugRoute
  "/redesign/settings/about": typeof RedesignSettingsAboutRoute
  "/redesign/settings/language": typeof RedesignSettingsLanguageRoute
  "/redesign/settings/notifications": typeof RedesignSettingsNotificationsRoute
  "/redesign/settings/providers": typeof RedesignSettingsProvidersRoute
  "/redesign/settings/theme": typeof RedesignSettingsThemeRoute
  "/books/$label/": typeof BooksLabelIndexRoute
  "/redesign/settings/": typeof RedesignSettingsIndexRoute
  "/books/$label/$step/$pageId": typeof BooksLabelStepPageIdRoute
  "/books/$label/$step/settings": typeof BooksLabelStepSettingsRoute
  "/books/$label/$step/": typeof BooksLabelStepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/redesign"
    | "/settings"
    | "/books/$label"
    | "/books/import"
    | "/books/new"
    | "/prompts/settings"
    | "/redesign/handoffs"
    | "/redesign/library"
    | "/redesign/settings"
    | "/redesign/"
    | "/books/$label/$step"
    | "/books/$label/debug"
    | "/redesign/settings/about"
    | "/redesign/settings/language"
    | "/redesign/settings/notifications"
    | "/redesign/settings/providers"
    | "/redesign/settings/theme"
    | "/books/$label/"
    | "/redesign/settings/"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/onboarding"
    | "/settings"
    | "/books/import"
    | "/books/new"
    | "/prompts/settings"
    | "/redesign/handoffs"
    | "/redesign/library"
    | "/redesign"
    | "/books/$label/debug"
    | "/redesign/settings/about"
    | "/redesign/settings/language"
    | "/redesign/settings/notifications"
    | "/redesign/settings/providers"
    | "/redesign/settings/theme"
    | "/books/$label"
    | "/redesign/settings"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step"
  id:
    | "__root__"
    | "/"
    | "/onboarding"
    | "/redesign"
    | "/settings"
    | "/books/$label"
    | "/books/import"
    | "/books/new"
    | "/prompts/settings"
    | "/redesign/handoffs"
    | "/redesign/library"
    | "/redesign/settings"
    | "/redesign/"
    | "/books/$label/$step"
    | "/books/$label/debug"
    | "/redesign/settings/about"
    | "/redesign/settings/language"
    | "/redesign/settings/notifications"
    | "/redesign/settings/providers"
    | "/redesign/settings/theme"
    | "/books/$label/"
    | "/redesign/settings/"
    | "/books/$label/$step/$pageId"
    | "/books/$label/$step/settings"
    | "/books/$label/$step/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  RedesignRoute: typeof RedesignRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  BooksLabelRoute: typeof BooksLabelRouteWithChildren
  BooksImportRoute: typeof BooksImportRoute
  BooksNewRoute: typeof BooksNewRoute
  PromptsSettingsRoute: typeof PromptsSettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/redesign": {
      id: "/redesign"
      path: "/redesign"
      fullPath: "/redesign"
      preLoaderRoute: typeof RedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/redesign/": {
      id: "/redesign/"
      path: "/"
      fullPath: "/redesign/"
      preLoaderRoute: typeof RedesignIndexRouteImport
      parentRoute: typeof RedesignRoute
    }
    "/redesign/settings": {
      id: "/redesign/settings"
      path: "/settings"
      fullPath: "/redesign/settings"
      preLoaderRoute: typeof RedesignSettingsRouteImport
      parentRoute: typeof RedesignRoute
    }
    "/redesign/library": {
      id: "/redesign/library"
      path: "/library"
      fullPath: "/redesign/library"
      preLoaderRoute: typeof RedesignLibraryRouteImport
      parentRoute: typeof RedesignRoute
    }
    "/redesign/handoffs": {
      id: "/redesign/handoffs"
      path: "/handoffs"
      fullPath: "/redesign/handoffs"
      preLoaderRoute: typeof RedesignHandoffsRouteImport
      parentRoute: typeof RedesignRoute
    }
    "/prompts/settings": {
      id: "/prompts/settings"
      path: "/prompts/settings"
      fullPath: "/prompts/settings"
      preLoaderRoute: typeof PromptsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/new": {
      id: "/books/new"
      path: "/books/new"
      fullPath: "/books/new"
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/import": {
      id: "/books/import"
      path: "/books/import"
      fullPath: "/books/import"
      preLoaderRoute: typeof BooksImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/books/$label": {
      id: "/books/$label"
      path: "/books/$label"
      fullPath: "/books/$label"
      preLoaderRoute: typeof BooksLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/redesign/settings/": {
      id: "/redesign/settings/"
      path: "/"
      fullPath: "/redesign/settings/"
      preLoaderRoute: typeof RedesignSettingsIndexRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/books/$label/": {
      id: "/books/$label/"
      path: "/"
      fullPath: "/books/$label/"
      preLoaderRoute: typeof BooksLabelIndexRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/redesign/settings/theme": {
      id: "/redesign/settings/theme"
      path: "/theme"
      fullPath: "/redesign/settings/theme"
      preLoaderRoute: typeof RedesignSettingsThemeRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/redesign/settings/providers": {
      id: "/redesign/settings/providers"
      path: "/providers"
      fullPath: "/redesign/settings/providers"
      preLoaderRoute: typeof RedesignSettingsProvidersRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/redesign/settings/notifications": {
      id: "/redesign/settings/notifications"
      path: "/notifications"
      fullPath: "/redesign/settings/notifications"
      preLoaderRoute: typeof RedesignSettingsNotificationsRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/redesign/settings/language": {
      id: "/redesign/settings/language"
      path: "/language"
      fullPath: "/redesign/settings/language"
      preLoaderRoute: typeof RedesignSettingsLanguageRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/redesign/settings/about": {
      id: "/redesign/settings/about"
      path: "/about"
      fullPath: "/redesign/settings/about"
      preLoaderRoute: typeof RedesignSettingsAboutRouteImport
      parentRoute: typeof RedesignSettingsRoute
    }
    "/books/$label/debug": {
      id: "/books/$label/debug"
      path: "/debug"
      fullPath: "/books/$label/debug"
      preLoaderRoute: typeof BooksLabelDebugRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/books/$label/$step": {
      id: "/books/$label/$step"
      path: "/$step"
      fullPath: "/books/$label/$step"
      preLoaderRoute: typeof BooksLabelStepRouteImport
      parentRoute: typeof BooksLabelRoute
    }
    "/books/$label/$step/": {
      id: "/books/$label/$step/"
      path: "/"
      fullPath: "/books/$label/$step/"
      preLoaderRoute: typeof BooksLabelStepIndexRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
    "/books/$label/$step/settings": {
      id: "/books/$label/$step/settings"
      path: "/settings"
      fullPath: "/books/$label/$step/settings"
      preLoaderRoute: typeof BooksLabelStepSettingsRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
    "/books/$label/$step/$pageId": {
      id: "/books/$label/$step/$pageId"
      path: "/$pageId"
      fullPath: "/books/$label/$step/$pageId"
      preLoaderRoute: typeof BooksLabelStepPageIdRouteImport
      parentRoute: typeof BooksLabelStepRoute
    }
  }
}

interface RedesignSettingsRouteChildren {
  RedesignSettingsAboutRoute: typeof RedesignSettingsAboutRoute
  RedesignSettingsLanguageRoute: typeof RedesignSettingsLanguageRoute
  RedesignSettingsNotificationsRoute: typeof RedesignSettingsNotificationsRoute
  RedesignSettingsProvidersRoute: typeof RedesignSettingsProvidersRoute
  RedesignSettingsThemeRoute: typeof RedesignSettingsThemeRoute
  RedesignSettingsIndexRoute: typeof RedesignSettingsIndexRoute
}

const RedesignSettingsRouteChildren: RedesignSettingsRouteChildren = {
  RedesignSettingsAboutRoute: RedesignSettingsAboutRoute,
  RedesignSettingsLanguageRoute: RedesignSettingsLanguageRoute,
  RedesignSettingsNotificationsRoute: RedesignSettingsNotificationsRoute,
  RedesignSettingsProvidersRoute: RedesignSettingsProvidersRoute,
  RedesignSettingsThemeRoute: RedesignSettingsThemeRoute,
  RedesignSettingsIndexRoute: RedesignSettingsIndexRoute,
}

const RedesignSettingsRouteWithChildren =
  RedesignSettingsRoute._addFileChildren(RedesignSettingsRouteChildren)

interface RedesignRouteChildren {
  RedesignHandoffsRoute: typeof RedesignHandoffsRoute
  RedesignLibraryRoute: typeof RedesignLibraryRoute
  RedesignSettingsRoute: typeof RedesignSettingsRouteWithChildren
  RedesignIndexRoute: typeof RedesignIndexRoute
}

const RedesignRouteChildren: RedesignRouteChildren = {
  RedesignHandoffsRoute: RedesignHandoffsRoute,
  RedesignLibraryRoute: RedesignLibraryRoute,
  RedesignSettingsRoute: RedesignSettingsRouteWithChildren,
  RedesignIndexRoute: RedesignIndexRoute,
}

const RedesignRouteWithChildren = RedesignRoute._addFileChildren(
  RedesignRouteChildren,
)

interface BooksLabelStepRouteChildren {
  BooksLabelStepPageIdRoute: typeof BooksLabelStepPageIdRoute
  BooksLabelStepSettingsRoute: typeof BooksLabelStepSettingsRoute
  BooksLabelStepIndexRoute: typeof BooksLabelStepIndexRoute
}

const BooksLabelStepRouteChildren: BooksLabelStepRouteChildren = {
  BooksLabelStepPageIdRoute: BooksLabelStepPageIdRoute,
  BooksLabelStepSettingsRoute: BooksLabelStepSettingsRoute,
  BooksLabelStepIndexRoute: BooksLabelStepIndexRoute,
}

const BooksLabelStepRouteWithChildren = BooksLabelStepRoute._addFileChildren(
  BooksLabelStepRouteChildren,
)

interface BooksLabelRouteChildren {
  BooksLabelStepRoute: typeof BooksLabelStepRouteWithChildren
  BooksLabelDebugRoute: typeof BooksLabelDebugRoute
  BooksLabelIndexRoute: typeof BooksLabelIndexRoute
}

const BooksLabelRouteChildren: BooksLabelRouteChildren = {
  BooksLabelStepRoute: BooksLabelStepRouteWithChildren,
  BooksLabelDebugRoute: BooksLabelDebugRoute,
  BooksLabelIndexRoute: BooksLabelIndexRoute,
}

const BooksLabelRouteWithChildren = BooksLabelRoute._addFileChildren(
  BooksLabelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  RedesignRoute: RedesignRouteWithChildren,
  SettingsRoute: SettingsRoute,
  BooksLabelRoute: BooksLabelRouteWithChildren,
  BooksImportRoute: BooksImportRoute,
  BooksNewRoute: BooksNewRoute,
  PromptsSettingsRoute: PromptsSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
