import { useEffect, useRef } from "react"
import { Sparkles } from "lucide-react"
import { Trans, useLingui } from "@lingui/react/macro"
import type { EasyReadSectionBlock } from "@/api/client"
import { cn } from "@/lib/utils"
import { tint } from "@/components/app/screens/pipeline/shared/plugins"
import { PageThumb } from "@/components/app/screens/pipeline/canvas/PageThumb"
import type { EasyReadBlockKey } from "./useEasyReadEdits"

export interface EasyReadPageGroup {
  pageId: string
  pageNumber: number
  blocks: EasyReadSectionBlock[]
}

export function EasyReadPageSection({
  label,
  group,
  accent,
  disabled,
  onUpdateEntry,
  onOpenPage,
}: {
  label: string
  group: EasyReadPageGroup
  accent: string
  disabled: boolean
  onUpdateEntry: (blockKey: EasyReadBlockKey, easyReadId: string, text: string) => void
  onOpenPage: (pageId: string) => void
}) {
  const { t } = useLingui()

  return (
    <section className="overflow-hidden rounded-xl border bg-card">
      <div className="flex items-center gap-3 border-b bg-muted/20 px-3.5 py-2.5">
        <button
          type="button"
          onClick={() => onOpenPage(group.pageId)}
          title={t`Open page preview`}
          aria-label={t`Open preview of page ${group.pageNumber}`}
          className="rounded-md transition-shadow hover:ring-2 hover:ring-ring focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <PageThumb label={label} pageId={group.pageId} sectionIndex={null} className="h-14 w-11" />
        </button>
        <div className="flex min-w-0 flex-col">
          <span className="text-[15px] font-semibold leading-tight text-foreground">
            <Trans>Page {group.pageNumber}</Trans>
          </span>
          <span className="text-[11px] text-muted-foreground">
            {group.blocks.length === 1 ? (
              <Trans>1 section</Trans>
            ) : (
              <Trans>{group.blocks.length} sections</Trans>
            )}
          </span>
        </div>
      </div>

      <div className="divide-y">
        {group.blocks.map((block) => (
          <div key={`${block.sectionId}:${block.sectionIndex}`} className="flex flex-col gap-3 p-3.5">
            <div className="flex items-center gap-2">
              <span
                className="inline-flex size-5 shrink-0 items-center justify-center"
                title={t`Generated by AI`}
                aria-label={t`Generated by AI`}
              >
                <Sparkles className="size-3.5" style={{ color: accent }} aria-hidden />
              </span>
              <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                {t`Section ${String(block.sectionIndex + 1)}`}
              </span>
              <span
                className="ml-auto rounded px-1.5 py-0.5 text-[10px] capitalize"
                style={{ background: tint(accent, 0.1), color: accent }}
              >
                {block.sectionType.replace(/_/g, " ")}
              </span>
            </div>

            {block.entries.map((entry) => {
              const unchanged = entry.text.trim() === entry.originalText.trim()
              return (
                <div key={entry.easyReadId} className="grid gap-3 md:grid-cols-2">
                  <div className="flex flex-col gap-1">
                    <p className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/60">
                      <Trans>Original</Trans>
                    </p>
                    <div className="rounded-md border bg-muted/30 p-2.5 text-[13px] leading-relaxed text-muted-foreground">
                      {entry.originalText}
                    </div>
                  </div>
                  <div className="flex flex-col gap-1">
                    <p
                      className="text-[10px] font-medium uppercase tracking-wider"
                      style={unchanged ? undefined : { color: accent }}
                    >
                      {unchanged ? (
                        <span className="text-muted-foreground/50">
                          <Trans>Easy Read</Trans>
                        </span>
                      ) : (
                        <Trans>Easy Read</Trans>
                      )}
                    </p>
                    <AutoTextarea
                      value={entry.text}
                      onChange={(text) => onUpdateEntry(block, entry.easyReadId, text)}
                      disabled={disabled}
                      muted={unchanged}
                      ariaLabel={t`Easy Read text`}
                    />
                  </div>
                </div>
              )
            })}
          </div>
        ))}
      </div>
    </section>
  )
}

function AutoTextarea({
  value,
  onChange,
  disabled,
  muted,
  ariaLabel,
}: {
  value: string
  onChange: (value: string) => void
  disabled?: boolean
  muted?: boolean
  ariaLabel?: string
}) {
  const ref = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    el.style.height = "auto"
    el.style.height = `${el.scrollHeight + 2}px`
  }, [value])

  return (
    <textarea
      ref={ref}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      aria-label={ariaLabel}
      rows={1}
      className={cn(
        "w-full resize-none overflow-hidden rounded-md border border-dashed bg-background/40 p-2.5 text-[13px] leading-relaxed text-foreground",
        "transition-colors hover:bg-muted/40 focus:border-solid focus:border-brand-400 focus:bg-background focus:outline-none focus:shadow-[0_0_0_3px_var(--brand-50)]",
        "disabled:opacity-60",
        muted && "opacity-55 hover:opacity-100 focus:opacity-100",
      )}
    />
  )
}
